Integrating Orc8r with Alertmanager Configurer
canonical/charmed-magma-orchestrator pull request #106
Opened 2022-09-22 10:16 UTC by Gmerold

# Description

Integrates Magma Orc8r with Alertmanager Configurer.

# Checklist:

- [X] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that validate the behaviour of the software
- [X] I validated that new and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2022-09-22 15:52 UTC, sanchezfdezjavier approved these changes
LGTM

2022-09-22 15:57 UTC, gruyaume commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> -    ALERTMANAGER_CONFIGURER_URL = "http://orc8r-alertmanager:9101"
:smile:

2022-09-22 15:57 UTC, gruyaume commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        alertmanager_configurer_relation = self.model.get_relation("alertmanager-configurer-k8s")
This makes me think that we should probably have a library to retrieve the info in this function. Out of scope of this PR though.

2022-09-23 10:49 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        alertmanager_configurer_relation = self.model.get_relation("alertmanager-configurer-k8s")
Technically, according to what I've recently learnt, we should extract pretty much all of our charms' business logic to libs. 
As for this particular case, if that's the only charm that requires this info (and I believe it is), perhaps creating an abstract method would make more sense (especially when there's also similar relation data published by `prometheus-k8s` and `alertmanager-k8s`)?
WDYT?

2022-09-23 10:50 UTC, sanchezfdezjavier approved these changes
LGTM

2022-09-23 19:14 UTC, ghislainbourgeois requested changes

2022-09-23 19:14 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        self._write_config_file()
This is called before validating that we can connect to the container, won't that fail in some cases?

2022-09-23 19:57 UTC, gruyaume commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        alertmanager_configurer_relation = self.model.get_relation("alertmanager-configurer-k8s")
I don't think I agree about "extracting all of a charm business logic to libraries". However I believe that logic about relations (ex. tls) and external systems (ex. k8s services) should indeed be inside of libraries.

2022-09-26 06:49 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        self._write_config_file()
Probably. Fixed.

2022-09-26 07:08 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        alertmanager_configurer_relation = self.model.get_relation("alertmanager-configurer-k8s")
Yeah, I'm not a fan of extracting **everything** either. 
For COS integration logic, I've drafted a task in our backlog - [TELCO-269](https://warthogs.atlassian.net/browse/TELCO-269). Feel free to update it.

2022-09-26 12:18 UTC, gruyaume approved these changes

2022-09-26 13:48 UTC, ghislainbourgeois approved these changes

2022-09-26 14:34 UTC, merged