Handles db_relation_departed event in orc8r_base_db lib
canonical/charmed-magma-orchestrator pull request #109
Opened 2022-09-27 12:36 UTC by saltiyazan

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-09-27 14:22 UTC, Gmerold requested changes
Changes look good to me, but I think we could use some tests for the new behavior.

2022-09-27 14:31 UTC, ghislainbourgeois requested changes
I also agree with @Gmerold that we would need a test to cover the behaviour.

2022-09-27 14:31 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.charm.unit.status = BlockedStatus("Waiting for db relation to be created")
Not sure this line is required, because when we call the pebble_ready method right after, we will be immediately updating the status based on the relation status.

2022-09-28 13:32 UTC, saltiyazan commented on orchestrator-bundle/orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.charm.unit.status = BlockedStatus("Waiting for db relation to be created")
Yes, that's a good point. I don't know why I added a separate handler :) it's fixed now.

2022-09-28 13:34 UTC, saltiyazan commented
> Changes look good to me, but I think we could use some tests for the new behavior.

Added new test cases, that make sure that the charm will go to `blocked` status if the `relation` is missing.
They don't care why is the relation missing. But I guess we trust the framework, and expect the relation to be actually removed and the handler to be called when the `relation_broken` event is emitted.

2022-09-29 06:55 UTC, Gmerold commented on orchestrator-bundle/orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.framework.observe(pebble_ready_event, self._configure_orc8r)
How about `_configure_charm`? Minor detail, but technically we're not configuring the whole Orc8r ;)

2022-09-29 07:04 UTC, Gmerold commented
> > Changes look good to me, but I think we could use some tests for the new behavior.
> 
> Added new test cases, that make sure that the charm will go to `blocked` status if the `relation` is missing. They don't care why is the relation missing. But I guess we trust the framework, and expect the relation to be actually removed and the handler to be called when the `relation_broken` event is emitted.

IMO it would be good to add additional tests actually simulating `relation_broken` anyway. It's not the matter of trust we put in the framework, but rather having a safety switch. Such tests would say `this is the behavior we expect in this case` (it's also sort of documentation) and if someone changes this behavior in the future, intentionally or accidentally, he should be informed about it; in this case by a failing test.
What do you think?

2022-09-29 07:30 UTC, saltiyazan commented
> > > Changes look good to me, but I think we could use some tests for the new behavior.
> > 
> > 
> > Added new test cases, that make sure that the charm will go to `blocked` status if the `relation` is missing. They don't care why is the relation missing. But I guess we trust the framework, and expect the relation to be actually removed and the handler to be called when the `relation_broken` event is emitted.
> 
> IMO it would be good to add additional tests actually simulating `relation_broken` anyway. It's not the matter of trust we put in the framework, but rather having a safety switch. Such tests would say `this is the behavior we expect in this case` (it's also sort of documentation) and if someone changes this behavior in the future, intentionally or accidentally, he should be informed about it; in this case by a failing test. What do you think?

My confusion came from the fact that the `pebble_ready` handler which is now renamed to `configure_orc8r` will be called, and that method is well covered by unit tests. But having something like `if db_relation is broken the charm should block` makes sense to add, as you said as a safety switch/documentation. :)

2022-10-03 11:39 UTC, saltiyazan commented on orchestrator-bundle/orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.framework.observe(pebble_ready_event, self._configure_orc8r)
Done

2022-10-03 11:39 UTC, saltiyazan commented on orchestrator-bundle/orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.charm.unit.status = BlockedStatus("Waiting for db relation to be created")
It seems like having a separate handler is a better idea, as we can't assume that the relation has been actually completely removed at the time `relation_broken` event is emitted.

2022-10-04 06:42 UTC, Gmerold commented on orchestrator-bundle/orc8r-libs/tests/test_orc8r_base_db.py
> +    @patch("charms.magma_orc8r_libs.v0.orc8r_base_db.Orc8rBase._db_relation_created")
We should avoid patching properties, especially private ones. You can just create a db relation instead.

2022-10-04 06:42 UTC, Gmerold commented on orchestrator-bundle/orc8r-libs/tests/test_orc8r_base_db.py
> +        "charms.magma_orc8r_libs.v0.orc8r_base_db.Orc8rBase._get_db_connection_string",
As above - I think this test should be adding the db relation and then removing it rather than faking relation availability and emitting `relation_broken` manually.

2022-10-04 17:46 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        self.charm.unit.status = BlockedStatus("Waiting for db relation to be created")
Agreed, and we are not calling the other handler after now.

2022-10-04 18:06 UTC, ghislainbourgeois approved these changes

2022-10-04 18:06 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-libs/tests/test_orc8r_base_db.py
> +        )
Small nitpick, but in tests with more than a few lines, I think separating the `given/when/then` sections with a newline helps reading:
```suggestion
        assert self.harness.charm.unit.status == ActiveStatus()
        
        self.harness.remove_relation(db_relation_id)
        
        assert self.harness.charm.unit.status == BlockedStatus(
            "Waiting for db relation to be created"
        )
```

2022-10-06 02:38 UTC, saltiyazan commented on orchestrator-bundle/orc8r-libs/tests/test_orc8r_base_db.py
> +    @patch("charms.magma_orc8r_libs.v0.orc8r_base_db.Orc8rBase._db_relation_created")
Done

2022-10-06 02:38 UTC, saltiyazan commented on orchestrator-bundle/orc8r-libs/tests/test_orc8r_base_db.py
> +        "charms.magma_orc8r_libs.v0.orc8r_base_db.Orc8rBase._get_db_connection_string",
Done

2022-10-06 02:53 UTC, saltiyazan commented on orchestrator-bundle/orc8r-libs/tests/test_orc8r_base_db.py
> +        )
Done

2022-10-18 12:37 UTC, Gmerold approved these changes

2022-10-19 15:44 UTC, merged