Handles db_relation_departed in charms
canonical/charmed-magma-orchestrator pull request #111
Opened 2022-09-27 12:48 UTC by saltiyazan

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- x ] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-09-27 14:31 UTC, Gmerold requested changes
What about unit tests for these charms?

2022-09-27 14:31 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +        await ops_test.model.wait_for_idle(apps=[APPLICATION_NAME], status="blocked", timeout=1000)
I think handling `relation_broken` should have a separate test.
WDYT?

2022-09-27 14:31 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        self.unit.status = BlockedStatus("Waiting for db relation to be created")
Do we need that if we're calling `self._on_magma_nms_magmalte_pebble_ready` next, which will do the same? Perhaps we don't need a separate callback function here (in that case `_on_magma_nms_magmalte_pebble_ready` would probably have to be renamed).

2022-09-27 14:31 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self.unit.status = BlockedStatus("Waiting for db relation to be created")
As above.

2022-09-27 14:31 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +        await ops_test.model.wait_for_idle(apps=[APPLICATION_NAME], status="blocked", timeout=1000)
As above.

2022-09-27 14:34 UTC, ghislainbourgeois reviewed
I pretty much have the same comments as @Gmerold

2022-09-28 13:28 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        self.unit.status = BlockedStatus("Waiting for db relation to be created")
Good point indeed, I don't know why I added a separate one.
I fixed it :)

2022-09-28 13:28 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self.unit.status = BlockedStatus("Waiting for db relation to be created")
Fixed

2022-09-28 13:32 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +        await ops_test.model.wait_for_idle(apps=[APPLICATION_NAME], status="blocked", timeout=1000)
> What about unit tests for these charms?

@ghislainbourgeois @Gmerold 
I renamed unit tests not to be testing `pebble_ready` but the functionality of `configuration`.
I don't think we need a separate test that mocks removing a relation. As far as I remember we should trust `ops` and should trust that the handler will be actually called if the event is emitted.
And the functionality (in this case the handler) is tested and covered by many test cases, but by emitting `pebble_ready`

2022-09-28 13:36 UTC, saltiyazan commented
> What about unit tests for these charms?

@ghislainbourgeois @Gmerold
I renamed unit tests not to be testing pebble_ready but the functionality of configuration.
I don't think we need a separate test that mocks removing a relation. As far as I remember we should trust ops and should trust that the handler will be actually called if the event is emitted.
And the functionality (in this case the handler) is tested and covered by many test cases, but by emitting pebble_ready

2022-09-29 10:46 UTC, Gmerold commented
> > What about unit tests for these charms?
> 
> @ghislainbourgeois @Gmerold I renamed unit tests not to be testing pebble_ready but the functionality of configuration. I don't think we need a separate test that mocks removing a relation. As far as I remember we should trust ops and should trust that the handler will be actually called if the event is emitted. And the functionality (in this case the handler) is tested and covered by many test cases, but by emitting pebble_ready

As already mentioned in the other PR, IMO it would be good to add additional tests actually simulating relation_broken anyway. It's not the matter of trust we put in the framework, but rather having a safety switch. Such tests would say this is the behavior we expect in this case (it's also sort of documentation) and if someone changes this behavior in the future, intentionally or accidentally, he should be informed about it; in this case by a failing test.

2022-10-03 11:40 UTC, saltiyazan commented
> > > What about unit tests for these charms?
> > 
> > 
> > @ghislainbourgeois @Gmerold I renamed unit tests not to be testing pebble_ready but the functionality of configuration. I don't think we need a separate test that mocks removing a relation. As far as I remember we should trust ops and should trust that the handler will be actually called if the event is emitted. And the functionality (in this case the handler) is tested and covered by many test cases, but by emitting pebble_ready
> 
> As already mentioned in the other PR, IMO it would be good to add additional tests actually simulating relation_broken anyway. It's not the matter of trust we put in the framework, but rather having a safety switch. Such tests would say this is the behavior we expect in this case (it's also sort of documentation) and if someone changes this behavior in the future, intentionally or accidentally, he should be informed about it; in this case by a failing test.

Unit test cases added.

2022-10-03 11:41 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +        await ops_test.model.wait_for_idle(apps=[APPLICATION_NAME], status="blocked", timeout=1000)
Seems like it's a good idea to have a separate handler, as we can't assume that the relation has been completely removed at the time `relation_broken` is emitted.

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        """Configures pebble layer and creates adming user of nms-magmalte.
```suggestion
        """Configures pebble layer and creates admin user of nms-magmalte.
```

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +            event (RelationJoinedEvent): Juju event
```suggestion
            event (RelationBrokenEvent): Juju event
```

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +            event (PebbleReadyEvent, CertificateAvailableEvent, RelationBrokenEvent): Juju event
```suggestion
            event (PebbleReadyEvent, CertificateAvailableEvent, RelationJoinedEvent): Juju event
```

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            event (RelationJoinedEvent): Juju event
```suggestion
            event (RelationBrokenEvent): Juju event
```

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/test_charm.py
> +        self.harness.charm.on.db_relation_broken.emit(self.harness.model.get_relation("db"))
Why not just remove the relation to trigger the event emission?

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.charm.on.db_relation_broken.emit(self.harness.model.get_relation("db"))
As below - why not remove the relation instead of emitting that manually?

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +        await self._deploy_postgresql(ops_test)
How about having this a separate test?

2022-10-04 06:56 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +        await ops_test.model.deploy("postgresql-k8s", application_name=DB_APPLICATION_NAME)
Separate test?

2022-10-11 08:19 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            event (RelationJoinedEvent): Juju event
Done

2022-10-11 08:19 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.charm.on.db_relation_broken.emit(self.harness.model.get_relation("db"))
Done

2022-10-11 08:20 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +        await ops_test.model.deploy("postgresql-k8s", application_name=DB_APPLICATION_NAME)
Done, testing only for blocked status

2022-10-11 08:20 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +        await self._deploy_postgresql(ops_test)
Done, testing only for blocked status

2022-10-11 08:46 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        if not self._service_is_running:
Shouldn't we raise an error here or something? I mean if the service is not running, this method will return, `_on_magma_nms_magmalte_pebble_ready` will think everything went smoothly and `ActiveStatus` will be set. Or am I missing something?

2022-10-11 08:46 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +    async def test_remove_db_application(self, ops_test, setup, build_and_deploy_charm):
Don't we want to test re-deployment of the DB to make sure charm gets back to `Active` status?

2022-10-11 08:46 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +    async def test_remove_db_application(self, ops_test, setup, build_and_deploy):
As above.

2022-10-11 10:06 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        if not self._service_is_running:
Correct, fixed :)

2022-10-11 10:06 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +    async def test_remove_db_application(self, ops_test, setup, build_and_deploy_charm):
Fixed

2022-10-11 10:06 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +    async def test_remove_db_application(self, ops_test, setup, build_and_deploy):
Fixed

2022-10-11 10:37 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        if not self._service_is_running:
Cool, but now it also needs to be handled somewhere, right?
BTW, perhaps having a custom exception would make sense? I guess we don't want our handler to catch any exception.

2022-10-17 11:34 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/test_charm.py
> +        assert self.harness.charm.unit.status == ActiveStatus()
We shouldn't have unrelated asserts in a unit test, there should probably be two different tests that we validate the behaviour for.

2022-10-17 11:34 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
>          await ops_test.model.wait_for_idle(apps=["postgresql-k8s"], status="active", timeout=1000)
No need to wait for idle for the postgresql-k8s charm. In reality we don't wait for it to be active before deploying more apps

2022-10-17 11:37 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/test_charm.py
> +        assert self.harness.charm.unit.status == ActiveStatus()
The goal of this is not to validate that it goes to `active` status, but to show that it will go to `blocked` after having been in `active` if a required dependency is removed. But I'm okay with removing this assert if that is cleaner.

2022-10-17 11:43 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/test_charm.py
> +        assert self.harness.charm.unit.status == ActiveStatus()
I understand, we don't need the first assert in this case

2022-10-17 12:28 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
>          await ops_test.model.wait_for_idle(apps=["postgresql-k8s"], status="active", timeout=1000)
Sure, makes sense, however I suggest to address it in a new PR :)

2022-10-17 12:35 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/test_charm.py
> +        assert self.harness.charm.unit.status == ActiveStatus()
removed :)

2022-10-18 07:06 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        """Configures pebble layer and creates adming user of nms-magmalte.
Done

2022-10-18 07:06 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +            event (RelationJoinedEvent): Juju event
Done

2022-10-18 07:06 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/test_charm.py
> +        self.harness.charm.on.db_relation_broken.emit(self.harness.model.get_relation("db"))
Done

2022-10-18 07:22 UTC, Gmerold approved these changes
Good job!

2022-10-18 13:11 UTC, gruyaume approved these changes

2022-10-18 13:55 UTC, ghislainbourgeois requested changes

2022-10-18 13:55 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            event.defer()
```suggestion
```

If the unit is not leader, we should just ignore the event, if not, this will create a defer loop.

2022-10-18 16:10 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            event.defer()
Correct, fixed.

2022-10-19 13:26 UTC, ghislainbourgeois requested changes

2022-10-19 13:26 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self._on_magma_orc8r_certifier_pebble_ready(event)
This change will prevent the non-leader units from having the pebble layer configured, is this what we really want?

2022-10-19 14:35 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self._on_magma_orc8r_certifier_pebble_ready(event)
So far we would allow only leader units to set `self.DB_NAME` which will block pebble layer configuration if not set, causing pebble not be configured by non-leader units.
So there is no change from that aspect here.
Do you propose to revisit the logic of this part?

2022-10-19 15:20 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self._on_magma_orc8r_certifier_pebble_ready(event)
No, I think this is ok for now, but this basically mean that having more than one unit for this charm is pointless. It is probably something we want to improve at a later time.

2022-10-19 15:21 UTC, ghislainbourgeois approved these changes

2022-10-20 07:22 UTC, merged