Dev handle relation broken events
canonical/charmed-magma-orchestrator pull request #113
Opened 2022-09-28 13:55 UTC by saltiyazan

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-10-14 08:36 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +            BlockedStatus("Waiting for relation(s) to be created: alertmanager-configurer-k8s"),
At this point we're already missing two relations, but the status only reports one. Do you think it would make sense to check for all missing relations?
PS. I know that once this missing relation joins, charm will detect and report any other missing relations.

2022-10-14 08:36 UTC, Gmerold commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +                "magma-orc8r-bootstrapper"
As above.

2022-10-14 08:36 UTC, Gmerold commented on orchestrator-bundle/orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        self.harness.remove_relation(
As above.

2022-10-14 08:53 UTC, saltiyazan commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +            BlockedStatus("Waiting for relation(s) to be created: alertmanager-configurer-k8s"),
Do you think having separate test cases is a better idea? for me it seems too repetitive, and it won't test any other behaviour than this one.  I mean here we can see that the charm is responding as its status stays blocked with new message :)
Another option would be to have one test with one relation, but then which relation gets chosen, and of course that is more loose.
Let me know your thoughts on which approach would be the best?

2022-10-14 10:22 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +            BlockedStatus("Waiting for relation(s) to be created: alertmanager-configurer-k8s"),
I was thinking more about the implementation rather than the test. Right now `on_relation_broken` sets the status for the relation that triggered the event. My idea was to actually iterate over the relations to find out the missing ones (just like we do in `configure_XXX_charm`.

2022-10-14 11:34 UTC, saltiyazan commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +            BlockedStatus("Waiting for relation(s) to be created: alertmanager-configurer-k8s"),
There is one problem with that: We are not sure that the relation is actually removed after it is broken :(
But we can call `_relation_created` to check if any other relations are still missing, but in that case we might miss the relation that is actually broken as `relation_created` might return `true` for that.
What do you think?

2022-10-14 11:44 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +            BlockedStatus("Waiting for relation(s) to be created: alertmanager-configurer-k8s"),
Oh yeah, there's that... true. Forget my comment then.

2022-10-14 11:46 UTC, Gmerold reviewed
It looks good to me. I'll wait with the approval for green itests tho (just in case there's some more changes).

2022-10-14 11:52 UTC, gruyaume commented on orchestrator-bundle/orc8r-orchestrator-operator/tests/unit/test_charm.py
> +    def _create_relations(self):
I am not sure about this method, its name suggests that it creates a relation but the content is much more complex as it contains multiple units, relation data on 2 sides. I think it should  take some input parameters and have some docstring.

2022-10-14 13:17 UTC, ghislainbourgeois requested changes

2022-10-14 13:17 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-orchestrator-operator/src/charm.py
> +    def _configure_magma_orc8r_orchestrator(  # noqa: C901
Since you simplified this method a lot, I think we can remove `# noqa: C901`

2022-10-17 07:45 UTC, saltiyazan commented on orchestrator-bundle/orc8r-orchestrator-operator/tests/unit/test_charm.py
> +    def _create_relations(self):
I changed it, let me know what do you think :)

2022-10-17 07:45 UTC, saltiyazan commented on orchestrator-bundle/orc8r-orchestrator-operator/src/charm.py
> +    def _configure_magma_orc8r_orchestrator(  # noqa: C901
Removed

2022-10-17 11:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +            relation_name: str
```suggestion
            relation_name (str): Relation name
```

2022-10-17 11:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +            remote_app: str
```suggestion
            remote_app (str): Remote application
```

2022-10-17 11:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +        """Creates a relation between orc8r-nginx and a remote app and activates it.
There is no such thing as activating a relation. Here we add a given key value that internally for Magma projects is used to send the information that the service running in the workload of the remote app is running.

2022-10-17 11:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +        self.assertEqual(
We have too many assert in a given unit test, unit tests should have 1 reason to fail, not multiple. It's fine to have multiple asserts if they all validate 1 behaviour but we shouldn't chain actions and asserts in 1 test.

2022-10-17 11:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +    def _on_required_relation_broken(self, event: RelationBrokenEvent):
Please add docstring

2022-10-17 12:15 UTC, saltiyazan commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +            relation_name: str
Fixed

2022-10-17 12:16 UTC, saltiyazan commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +            remote_app: str
Fixed

2022-10-17 12:16 UTC, saltiyazan commented on orchestrator-bundle/orc8r-nginx-operator/tests/unit/test_charm.py
> +        """Creates a relation between orc8r-nginx and a remote app and activates it.
Fixed

2022-10-17 12:16 UTC, saltiyazan commented on orchestrator-bundle/orc8r-metricsd-operator/tests/unit/test_charm.py
> +        self.assertEqual(
The goal here was to avoid having separate test cases for the same thing (I felt it would be very repetitive)
However I moved them to separate cases now.

2022-10-17 12:16 UTC, saltiyazan commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +    def _on_required_relation_broken(self, event: RelationBrokenEvent):
done

2022-10-18 07:24 UTC, Gmerold approved these changes

2022-10-18 13:22 UTC, gruyaume approved these changes

2022-10-18 13:49 UTC, ghislainbourgeois approved these changes

2022-10-18 15:55 UTC, merged