Adding lib for exposing rootCA
canonical/charmed-magma-orchestrator pull request #115
Opened 2022-09-29 10:42 UTC by Gmerold

# Description

Adds a library to `magma-orc8r-certifier` to expose `rootCA`.
This PR is part of [TELCO-184](https://warthogs.atlassian.net/jira/software/c/projects/TELCO/boards/51?selectedIssue=TELCO-184). 

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-29 10:51 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_root.py
> +class CertRootRequires(Object):
A provider example is missing :)

2022-09-29 10:52 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_root.py
> +            charm.on[relationship_name].relation_joined, self._on_relation_changed
shouldn't is be observing `CertRootRequirerCharmEvents` such as `certificate_available`?

2022-09-29 10:56 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_cert_root.py
> +        self.harness.charm.root_cert.set_certificate(
I'd say this should be part of the charm itself, and be called when handling `certificate_request` event

2022-09-29 10:57 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_provider/src/charm.py
> +        self.root_cert = CertRootProvides(self, "cert-root")
We could observe `certificate_request` and set the certificate.

2022-09-30 06:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_root.py
> +class CertRootRequires(Object):
Docstrings improved.

2022-09-30 06:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_root.py
> +            charm.on[relationship_name].relation_joined, self._on_relation_changed
Agreed. Fixed.

2022-09-30 06:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_cert_root.py
> +        self.harness.charm.root_cert.set_certificate(
You're right. Corrected.

2022-09-30 06:49 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_provider/src/charm.py
> +        self.root_cert = CertRootProvides(self, "cert-root")
Agreed. Fixed.

2022-09-30 08:27 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_provider/src/charm.py
> +        logger.error("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
Is this leftover from debugging :D ?

2022-09-30 08:29 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_provider/src/charm.py
> +        logger.error("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
Yes :D Removed.

2022-09-30 08:29 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_provider/src/charm.py
> +class WhateverCharm(CharmBase):
Do we need also a `requirer` dummy charm for testing the other side? or is it enough as is now?

2022-09-30 09:31 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_provider/src/charm.py
> +class WhateverCharm(CharmBase):
Well, I wanted to make it fast and minimal, but you're right, let's not cut corners. 
Added ;)

2022-09-30 13:08 UTC, saltiyazan commented
Looks good to me now :)
One general question I still have, if the library should care about the events being emitted by a `leader` unit?
or are you leaving it to the implementing charm to decide?

2022-09-30 13:08 UTC, saltiyazan approved these changes

2022-09-30 14:31 UTC, Gmerold commented
> Looks good to me now :) One general question I still have, if the library should care about the events being emitted by a `leader` unit? or are you leaving it to the implementing charm to decide?

It doesn't really matter. When `Provider` pushes the cert to the relation data bag, `Requirer` sees the `relation_changed` event. Using `event.unit` it knows exactly which unit has the data, fetches it and emits `certificate_available` with the cert inside the event.

2022-09-30 14:32 UTC, sanchezfdezjavier requested changes

2022-09-30 14:32 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_ca_requirer/src/charm.py
> +#!/usr/bin/env python3
Do we need this line?

2022-09-30 14:32 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_ca_provider/src/charm.py
> +#!/usr/bin/env python3
Do we need this line?

2022-09-30 14:32 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_root_ca.py
> +            self.on.certificate_available.emit(certificate=certificate)
```suggestion
        if certificate := relation_data[event.unit].get("certificate"):
            self.on.certificate_available.emit(certificate=certificate)
```

2022-09-30 15:07 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_ca_requirer/src/charm.py
> +#!/usr/bin/env python3
We don't need need it. I mean charm will work without it, but then again we keep it in all of our charms.

2022-09-30 15:07 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/lib/charms/magma_orc8r_certifier/v0/test_charms/test_root_ca_provider/src/charm.py
> +#!/usr/bin/env python3
As above.

2022-09-30 15:10 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_root_ca.py
> +            self.on.certificate_available.emit(certificate=certificate)
I guess that's just matter of personal preferences, but I think that the current version is easier to read. If you don't mind, I'd keep it as is.

2022-09-30 15:27 UTC, sanchezfdezjavier approved these changes

2022-09-30 15:39 UTC, merged