Adds series to bootstrapper integration tests
canonical/charmed-magma-orchestrator pull request #137
Opened 2022-10-21 20:44 UTC by gruyaume

# Description

Adds series to bootstrapper integration tests

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-22 00:44 UTC, ghislainbourgeois approved these changes

2022-11-16 14:26 UTC, ghislainbourgeois requested changes

2022-11-16 14:26 UTC, ghislainbourgeois commented on orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        additional_environment_variables: dict = {},
This is dangerous, in most cases, because the default list or dict that is created will be the same object for all instances. In this case, it will probably not cause any issues, but I would change it anyway to get rid of the dangerous construct.

The best way to deal with default objects is to have the default set to `None` and immediately check it:

```
def f(my_list: list = None):
    if my_list is None:
        my_list = []
```

2022-11-16 14:26 UTC, ghislainbourgeois commented on orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        additional_environment_variables: dict = {},
As above

2022-11-16 14:43 UTC, saltiyazan commented on orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base.py
> +        additional_environment_variables: dict = {},
Fixed :)

2022-11-16 14:43 UTC, saltiyazan commented on orc8r-libs/lib/charms/magma_orc8r_libs/v0/orc8r_base_db.py
> +        additional_environment_variables: dict = {},
Fixed

2022-11-16 15:14 UTC, ghislainbourgeois approved these changes

2022-11-16 16:11 UTC, merged