Adds an option to promote all charms
canonical/charmed-magma-orchestrator pull request #139
Opened 2022-10-25 09:33 UTC by saltiyazan

# Description

Adds an `all` option to promote all of the charms.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-10-26 07:11 UTC, ghislainbourgeois requested changes

2022-10-26 07:11 UTC, ghislainbourgeois commented on .github/workflows/charms.promote.yaml
> +          if: github.event.inputs.charm-name != 'all'
This `if` is not at the same indentation level as the other block, can you validate which is right?

2022-10-26 08:29 UTC, saltiyazan commented on .github/workflows/charms.promote.yaml
> +          if: github.event.inputs.charm-name != 'all'
Fixed. I changed the whole logic of condition checks, it wasn't working as it was.

2022-10-27 06:22 UTC, ghislainbourgeois approved these changes

2022-11-02 09:51 UTC, Gmerold approved these changes

2022-11-04 08:49 UTC, merged