Telco 344 fixing unable to relate multiple agws to one orc8r
canonical/charmed-magma-orchestrator pull request #141
Opened 2022-10-28 12:31 UTC by Gmerold

# Description

Updates the `magma-orchestrator-interface` library in `orc8r-nginx-operator` to fix the bug preventing relating multiple AGWs to one Orc8r.
Additionally adds `bundle-local.yaml` which must have been deleted accidentally.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-29 10:41 UTC, gruyaume requested changes

2022-10-29 10:41 UTC, gruyaume commented on bundle-local.yaml
> +bundle: kubernetes
I don't think we want this. The existing bundle template can be used for generating the local bundle.

2022-10-31 13:00 UTC, Gmerold commented on bundle-local.yaml
> +bundle: kubernetes
Oh, didn't know that.
Removed.

2022-11-02 15:49 UTC, gruyaume approved these changes

2022-11-02 15:52 UTC, saltiyazan approved these changes

2022-11-02 22:23 UTC, merged