Adding fluentd cert generation
canonical/charmed-magma-orchestrator pull request #142
Opened 2022-11-28 10:01 UTC by Gmerold

# Description

- Adds fluentd certificate and private key generation
- Adds cert-fluentd library to `orc8r-certifier` (not officially registered yet)
- Adds `cert-fluentd` relation to `orc8r-certifier`

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-28 10:34 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +        )
Why do we need this event listener? I don't get why we need it having the one below listening to `relation_changed`

2022-11-28 11:42 UTC, Gmerold commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +        )
Theoretically, we don't necessarily need it, because `relation_joined` also fires `relation_changed`, but I think having two separate handlers improves visibility on charm's behavior.

2022-11-28 14:50 UTC, ghislainbourgeois requested changes

2022-11-28 14:50 UTC, ghislainbourgeois commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +To get started using the library, you just need to fetch the library using `charmcraft`.
```suggestion
To get started using the library, you need to fetch the library using `charmcraft`.
```
Using words like `just` and `simply` is usually superfluous. This blog post is great on the subject: https://justsimply.dev/

2022-11-28 15:00 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +        )
Won't this cause `_on_realtion_changed` to be triggered twice when `on_relation_joined` occurs? Besides, if we aim to handle `relation_joined`, shouldn't `_on_relation_changed` accept `RelationJoinedEvent` as a parameter too?

2022-11-28 15:28 UTC, Gmerold commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +To get started using the library, you just need to fetch the library using `charmcraft`.
Removed.
Also update rootca lib.

2022-11-28 15:29 UTC, Gmerold commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +        )
It won't be fired twice. 
Also fixed typing in method signature.

2022-11-28 15:32 UTC, ghislainbourgeois approved these changes

2022-11-28 15:57 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +        )
Why wouldn't it? I don't get it

2022-11-28 18:15 UTC, gruyaume requested changes

2022-11-28 18:15 UTC, gruyaume commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +# Copyright 2022 Canonical Ltd.
Why is `certifier` involved here?  `fluentd` should generate its own private key and certificates no?

2022-11-29 09:33 UTC, Gmerold commented on orc8r-certifier-operator/lib/charms/magma_orc8r_certifier/v0/cert_fluentd.py
> +# Copyright 2022 Canonical Ltd.
The thing is that the `certifier.key` and `certifier.pem` are used to generate `fluentd.pem`:
```
openssl x509 -req -in fluentd.csr \
  -CA certifier.pem -CAkey certifier.key -CAcreateserial \
  -out fluentd.pem -days 3650 -sha256
```
Would you rather pass the `certifier.key` and `certifier.pem` to Fluentd charm and generate certs there?

2022-12-01 12:06 UTC, closed without merging