Adding fluentd charm
canonical/charmed-magma-orchestrator pull request #144
Opened 2022-12-02 17:13 UTC by Gmerold

# Description

Adds fluentd charm.
**NOTE:**
This is just an initial PR and this charm is **not ready** to be added to the bundle yet. In current shape, it won't even start, because fluentd certificates are still missing. Fluentd certs are handles in [this story](https://warthogs.atlassian.net/browse/TELCO-352).

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-02 17:24 UTC, gruyaume commented
I don't think the charm should be part of the charmed magma repo, we should leverage the existing [project](https://github.com/canonical/fluentd-elasticsearch-operator) and make the changes there.

2022-12-02 18:20 UTC, gruyaume requested changes

2022-12-02 18:20 UTC, gruyaume commented on fluentd/src/config_files/output.conf.j2
> +<match eventd>
There are 2 blocks here, do we know if they are both used in Magma? Do we see logs tagged with `eventd` and with `magma`

2022-12-02 18:20 UTC, gruyaume commented on fluentd/src/charm.py
> +    def _cert_is_stored(self, cert_path: str) -> bool:
The method name doesn't match with what it does. Here we could pass it anything and it would validate that it exists on the container (not necessariliy a cert)

2022-12-02 18:20 UTC, gruyaume commented on fluentd/src/charm.py
> +    REQUIRED_RELATIONS = ["cert-certifier"]
Fluentd requires a relation to anything that gives it certificates, not specifically certifier.

2022-12-02 18:20 UTC, gruyaume commented on fluentd/README.md
> +- **elasticsearch-ssl-version**: SSL version. Defaults to TLSv1.
That doesn't need to be a config, we can just use the most recent in the charm

2022-12-02 18:20 UTC, gruyaume commented on fluentd/README.md
> +- **elasticsearch-schema**: "http" or "https" depending on whether the ElasticSearch endpoint
This should be automatically generated if we leverage the tls certificates relation

2022-12-02 18:20 UTC, gruyaume commented on fluentd/README.md
> +- **domain**: Fluentd domain (same as Orc8r domain).
```suggestion
- **domain**: Fluentd domain
```

2022-12-02 18:20 UTC, gruyaume commented on fluentd/src/charm.py
> +                "external-dns.alpha.kubernetes.io/hostname": f"fluentd.{self._domain_config}"
Is this really needed?

2022-12-02 18:20 UTC, gruyaume commented on fluentd/src/charm.py
> +            domain=self._domain_config,
I don't think `domain` is used in the template

2022-12-02 18:20 UTC, gruyaume commented on fluentd/README.md
> +- **fluentd-chunk-limit-size**: The size limit of the received chunk. If the chunk size is larger
I'd remove the config for this and keep the charm minimal

2022-12-02 18:20 UTC, gruyaume commented on fluentd/README.md
> +- **fluentd-queue-limit-length**: The limit of the chunk queue length. If the chunk queue length
I'd remove the config for this and keep the charm minimal

2022-12-02 18:20 UTC, gruyaume commented on fluentd/src/charm.py
> +    BASE_CERTS_PATH = "/certs"
How does fluentd knows to use those certs? I see nothing pointing to this path

2022-12-02 18:20 UTC, gruyaume commented on fluentd/README.md
> +
I'd add a warning to tell that this charm is hardcoded to work with Magma only.

2022-12-02 18:20 UTC, gruyaume commented on fluentd/charmcraft.yaml
> +parts:
Is this part necessary?

2022-12-05 12:20 UTC, Gmerold commented on fluentd/README.md
> +
The last line of the description already says `This fluentd charm 
is specifically built to forward Magma logs to elasticsearch.`
Do you think it should be more exposed? I mean this charm is under `charmed-magma-orchestrator` repo anyway.

2022-12-05 12:21 UTC, Gmerold commented on fluentd/charmcraft.yaml
> +parts:
No, I forgot to remove it after changing `ops` not be fetched from git.
Removed.

2022-12-05 12:22 UTC, Gmerold commented on fluentd/src/charm.py
> +    BASE_CERTS_PATH = "/certs"
Once certs are in place, `forward-input.conf` will tell fluentd to use this path:
```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
  <transport tls>
    ca_path /certs/certifier.pem
    cert_path /certs/fluentd.pem
    private_key_path /certs/fluentd.key
    client_cert_auth true
  </transport>
</source>
```

2022-12-05 12:23 UTC, Gmerold commented on fluentd/src/charm.py
> +            domain=self._domain_config,
Ups, my bad.
Removed.

2022-12-05 12:23 UTC, Gmerold commented on fluentd/src/charm.py
> +                "external-dns.alpha.kubernetes.io/hostname": f"fluentd.{self._domain_config}"
No, not really.

2022-12-05 12:23 UTC, Gmerold commented on fluentd/README.md
> +- **domain**: Fluentd domain (same as Orc8r domain).
`domain` removed completely.

2022-12-05 12:24 UTC, Gmerold commented on fluentd/src/charm.py
> +    def _cert_is_stored(self, cert_path: str) -> bool:
Updated the name.

2022-12-05 12:25 UTC, Gmerold commented on fluentd/src/config_files/output.conf.j2
> +<match eventd>
Not sure. Didn't get that far with Magma usage ;) I'd assume it is needed, because that's extracted directly from the official deployment.

2022-12-05 12:28 UTC, Gmerold commented on fluentd/src/charm.py
> +    REQUIRED_RELATIONS = ["cert-certifier"]
If fact we need certifier cert specifically. That's because when AGW pushes logs to fluentd it uses cert signed by the `certifier.pem` and fluentd needs to validate that cert.
Anything providing certs is true for fluentd cert only.

2022-12-05 13:56 UTC, gruyaume commented on fluentd/README.md
> +
Yeah if we keep it under charmed-magma I don'y really care so you can ignore my messge.

2022-12-05 15:36 UTC, Gmerold commented on fluentd/src/charm.py
> +    REQUIRED_RELATIONS = ["cert-certifier"]
Certs related stuff removed from this PR. It will be addressed in another PR.

2022-12-05 15:36 UTC, Gmerold commented on fluentd/README.md
> +- **elasticsearch-schema**: "http" or "https" depending on whether the ElasticSearch endpoint
Certs related stuff removed from this PR. It will be addressed in another PR.

2022-12-05 15:37 UTC, Gmerold commented on fluentd/README.md
> +- **fluentd-chunk-limit-size**: The size limit of the received chunk. If the chunk size is larger
As discussed this can be useful in case of bigger deployments.

2022-12-05 15:37 UTC, Gmerold commented on fluentd/README.md
> +- **fluentd-queue-limit-length**: The limit of the chunk queue length. If the chunk queue length
As above.

2022-12-05 15:37 UTC, Gmerold commented on fluentd/README.md
> +- **elasticsearch-ssl-version**: SSL version. Defaults to TLSv1.
Certs related stuff removed from this PR. It will be addressed in another PR.

2022-12-06 22:11 UTC, gruyaume commented on fluentd/README.md
> +# fluentd
```suggestion
# fluentd-elasticsearch
```

2022-12-06 22:11 UTC, gruyaume commented on fluentd/metadata.yaml
> +      - storage: certs
I'd suggest removing certs and re-adding that in the PR that adds certs

2022-12-06 22:11 UTC, gruyaume commented on fluentd/metadata.yaml
> +  certs:
I'd suggest removing certs and re-adding that in the PR that adds certs

2022-12-06 22:11 UTC, gruyaume commented on fluentd/src/charm.py
> +
All the config files that are static can be written to on install while the dynamic ones can be written to on config_changed. And like this we can also drop the `pebble_ready` handler and move it all to the config_changed.

2022-12-06 22:11 UTC, gruyaume commented on fluentd/src/charm.py
> +            service_name="fluentd",
```suggestion
```

2022-12-06 22:16 UTC, gruyaume commented on fluentd/src/charm.py
> +        elasticsearch_url_split = elasticsearch_url.split(":")  # type: ignore[union-attr]
You can get rid of the `# type: ignore[union-attr]` if you handle the case where there is no elasticsearch_url set

2022-12-06 22:16 UTC, gruyaume commented on fluentd/src/charm.py
> +    def _get_fluentd_config(self) -> dict:
I'm not sure of the value of combining the 2 together in 1 get, I thing having properties for the 2 values is just fine

2022-12-06 22:16 UTC, gruyaume commented on fluentd/src/charm.py
> +    def _get_fluentd_config(self) -> dict:
```python
@property
def _config_fluentd_chunk_limit_size:
    return self.model.config.get("fluentd-chunk-limit-size")
```

2022-12-06 22:16 UTC, gruyaume commented on fluentd/src/charm.py
> +        """Checks whether given Elasticsearch URL is valid or not.
```suggestion
        """Returns whether given Elasticsearch URL is valid or not.
```

2022-12-07 09:15 UTC, Gmerold commented on fluentd/README.md
> +# fluentd
I wanted this to match the name of the charm; and charm name can't be `fluentd-elasticsearch`, because it's already taken.

2022-12-07 09:15 UTC, Gmerold commented on fluentd/metadata.yaml
> +      - storage: certs
Sure.

2022-12-07 09:15 UTC, Gmerold commented on fluentd/metadata.yaml
> +  certs:
Sure.

2022-12-07 09:15 UTC, Gmerold commented on fluentd/src/charm.py
> +
Done.

2022-12-07 14:25 UTC, gruyaume commented on fluentd/README.md
> +# fluentd
Well it's taken by us. We can replace fluentd with fluentd-elasticsearch and this instance here becomes this charm.

2022-12-07 20:46 UTC, Gmerold commented on fluentd/README.md
> +# fluentd
Renamed. Old repo archived.

2022-12-09 16:01 UTC, ghislainbourgeois approved these changes

2022-12-12 12:58 UTC, gruyaume approved these changes

2022-12-12 12:59 UTC, merged