Telco 351 fluentd certs
canonical/charmed-magma-orchestrator pull request #145
Opened 2022-12-12 13:43 UTC by Gmerold

# Description

Adds certificates support to fluentd charm.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-12 20:08 UTC, ghislainbourgeois requested changes

2022-12-12 20:08 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +        if not self._application_private_key:
I must be missing something, I cannot find where this is defined.

2022-12-12 20:08 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +            event.defer()
I do not think we should defer here, we should get a new event when the CSR is added.

2022-12-12 20:08 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +    def _on_fluentd_certificate_creation_request(
I do not see tests for this new behavior.

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._fluentd_certificates.request_certificate_creation(self._fluentd_csr.encode())
We could call `_request_certificate_based_on_existing_private_key()` here and remove some duplication.

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        return True
```suggestion
        return bool(self._fluentd_private_key)
```

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        return True
```suggestion
        return bool(self._fluentd_csr)
```

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +            permissions=0o777,
```suggestion
            permissions=0o666,
        )
        self._write_to_file(
            destination_path=Path(f"{self.CONFIG_DIRECTORY}/general.conf"),
            content=self._read_file(Path(f"{self.CONFIG_SOURCE_DIRECTORY}/general.conf")),
            permissions=0o666,
        )
        self._write_to_file(
            destination_path=Path(f"{self.CONFIG_DIRECTORY}/system.conf"),
            content=self._read_file(Path(f"{self.CONFIG_SOURCE_DIRECTORY}/system.conf")),
            permissions=0o666,
```

I don't think we need those to be executable.

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +            permissions=0o777,
```suggestion
            permissions=0o666,
```

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        return False
```suggestion
        return bool(pattern.match(self._domain_config))
```

2022-12-12 20:08 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        return True
```suggestion
        return bool(self.model.get_relation(relation_name))
```

2022-12-12 20:16 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +        if not self._application_private_key:
It's a property pointing to the `certifier.key` (line 1210).

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        """Generates Fluentd CSR and saves it in the container."""
```suggestion
        """Generates Fluentd CSR and saves it in the peer relation data."""
```

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        """Generates Fluentd private key and saves it in the container."""
```suggestion
        """Generates Fluentd private key and saves it in the peer relation data."""
```

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        if not self._container.can_connect():
This condition shouldn't be involved as this won't get inside of the contianer.

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +            self._request_fluentd_certificates()
I don't think this should be in this `_configure` handler. At least it doesn't match with what the methon names says it does.

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +            self._request_fluentd_certificates()
I think we should request certiicates when the `certifier` relation is joined.

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        logger.info(f"Writing config file to {destination_path}")
I'd put the logging after the `push` and write `Config file wrote to {destination_path}`. We typically put logs once an action is completed.

2022-12-12 21:24 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/config_files/forward-input.conf
> +    ca_path /certs/ca.pem
I'd recommend use `jinja` and  leverage the `CERTIFICATES_DIRECTORY` variable instead of hardoding `/certs/`.

2022-12-13 14:10 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +        if not self._application_private_key:
Thanks

2022-12-14 11:34 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        logger.info(f"Writing config file to {destination_path}")
Changed.

2022-12-14 11:36 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        if not self._container.can_connect():
Yes, it's a leftover after my initial idea of pushing certs to the container directly. Having replicas made me realize it's stupid.
Remove.

2022-12-14 11:36 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        """Generates Fluentd private key and saves it in the container."""
Updated.

2022-12-14 11:36 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        """Generates Fluentd CSR and saves it in the container."""
Updated.

2022-12-14 11:37 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +            event.defer()
True. 
Removed.

2022-12-14 11:42 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._fluentd_certificates.request_certificate_creation(self._fluentd_csr.encode())
Updated.

2022-12-14 11:42 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        return True
Done.

2022-12-14 11:42 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        return True
Done.

2022-12-14 11:43 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +            permissions=0o777,
Yeah, I guess we don't. I just blindly copied the permissions from the official deployment.
Updated.

2022-12-14 11:43 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        return True
Updated.

2022-12-14 11:43 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        return False
Updated.

2022-12-14 11:43 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +            permissions=0o777,
Updated.

2022-12-14 21:36 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/config_files/forward-input.conf
> +    ca_path /certs/ca.pem
Sure. Done.

2022-12-14 23:11 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +    def _on_fluentd_certificate_creation_request(
Right, I forgot to write them :)
Added.

2022-12-30 12:44 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +            self._request_fluentd_certificates()
Sure.
Done.

2023-01-03 13:35 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._save_fluentd_private_key_to_file(self._fluentd_private_key)
I think `push_to_workload` would be a better word than `save`.

2023-01-03 13:35 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(  # noqa: C901
I'm not a fan of the huge `_configure`. I think each of the top level event handler (certificate_available and config_changed` could do all the necessary validations appropriate to their events (if not <blabla> then blocked) then call this `_configure` method (thay I'd rename to `push_config_files_to_workload`) then put the status to active. Overall this would mean more code but would make the event handling and code understanding a bit simpler.

2023-01-03 13:35 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _write_static_config_files(self) -> None:
I'd replace `write` with `push_to_workload`

2023-01-17 14:56 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._save_fluentd_private_key_to_file(self._fluentd_private_key)
Changed.

2023-01-17 14:56 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(  # noqa: C901
Refactored.

2023-01-17 14:56 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _write_static_config_files(self) -> None:
Changed.

2023-01-18 13:22 UTC, gruyaume reviewed
I'm not yet done doing the review but here are some initial thoughts.

2023-01-18 13:22 UTC, gruyaume commented on fluentd-elasticsearch-operator/metadata.yaml
> +    description: Fluetnd certs
```suggestion
    description: Fluentd certs
```

2023-01-18 13:22 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(self) -> None:
I don't think we need this method `configure`. If we keep it, I'd rather change its name (`configure is way too generic). We can be directly calling the different method in it (`_push_fluentd_certs_to_workload`, _push_dynamic_config_files_to_workload, _configure_pebble_layer`)

2023-01-18 13:22 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        logger.error(fluentd_csr)
Why this error?

2023-01-18 13:22 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
>          """Renders fluetnd config file from a given Jinja template.
```suggestion
        """Renders fluentd config file from a given Jinja template.
```

2023-01-18 13:22 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _push_dynamic_config_files_to_workload(self) -> None:
This is marked as dynamic but the certs diretory won't change over the lifecycle of the charms.

2023-01-18 13:42 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        logger.error(fluentd_csr)
Just a debugging leftover. Removed.

2023-01-18 13:42 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
>          """Renders fluetnd config file from a given Jinja template.
Done.

2023-01-18 13:43 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _push_dynamic_config_files_to_workload(self) -> None:
True. Moved the file to static configs.

2023-01-18 13:43 UTC, Gmerold commented on fluentd-elasticsearch-operator/metadata.yaml
> +    description: Fluetnd certs
Done.

2023-01-18 13:44 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(self) -> None:
I'd keep the method to avoid duplications. 
How about `_configure_and_start_workload`?

2023-01-18 16:35 UTC, gruyaume commented on .github/workflows/fluentd.yml
> +    runs-on: self-hosted
In this case do we need to run it on the self-hosted runner? I'd really try to minimize the number of integration tests running on our runner, knowing how flaky they are.

2023-01-18 16:36 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(self) -> None:
I am fine with duplication, especially when it increases simplicity and readability.

2023-01-19 09:15 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(self) -> None:
After refactoring, `_configure_and_start_workload` has
```python
self.unit.status = MaintenanceStatus("Configuring pod")
self._push_fluentd_certs_to_workload()
self._push_dynamic_config_files_to_workload()
self._configure_pebble_layer()
self.unit.status = ActiveStatus()
```
I'm not sure whether unwrapping this will improve readability. 
If we take the first callback using this function:
```python
def _on_fluentd_pebble_ready(self, event: PebbleReadyEvent):
    """Triggered when Fluentd pebble is ready.

    Args:
        event: Juju event (PebbleReadyEvent)
    """
    if not self._relations_created:
        event.defer()
        return
    if not self._fluentd_certificates_stored_in_peer_relation_data:
        self.unit.status = WaitingStatus("Waiting for Fluentd certificates to be available")
        return
    self._configure_and_start_workload()
```
For understanding charm's workflow, on a high level, I'd say it's easier to have it as is - if relations are created and certs are stored, configure and start the workload.

2023-01-19 12:26 UTC, Gmerold commented on .github/workflows/fluentd.yml
> +    runs-on: self-hosted
I've checked again today and yes, we need bigger runner for this one (seems to me that everything that requires `certifier` needs to run on self-hosted runners).

2023-01-19 19:05 UTC, gruyaume commented on .github/workflows/fluentd.yml
> +    runs-on: self-hosted
:'(

2023-01-19 19:06 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _configure(self) -> None:
Okokokok let's keep it as is.

2023-01-20 18:53 UTC, ghislainbourgeois approved these changes
Small nitpick, there is an empty file `orc8r-nginx-operator/actions.yaml` committed, if it is not required, can you please remove it?

2023-01-20 18:53 UTC, ghislainbourgeois commented on .github/workflows/fluentd.yml
> +          /usr/bin/sg microk8s -c "microk8s kubectl -n kube-system rollout status deployment/hostpath-provisioner"
Don't we need metallb also?

2023-01-20 18:53 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/metadata.yaml
> +    minumum-size: 1M
```suggestion
    minimum-size: 1M
```

2023-01-20 18:53 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _renew_cerificate(self) -> None:
```suggestion
    def _renew_certificate(self) -> None:
```

2023-01-23 12:37 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _renew_cerificate(self) -> None:
Fixed.

2023-01-23 12:37 UTC, Gmerold commented on fluentd-elasticsearch-operator/metadata.yaml
> +    minumum-size: 1M
Fixed.

2023-01-23 12:58 UTC, Gmerold commented on .github/workflows/fluentd.yml
> +          /usr/bin/sg microk8s -c "microk8s kubectl -n kube-system rollout status deployment/hostpath-provisioner"
Not for the integration tests we have. They focus on the charm from Juju perspective. 
We could think about adding additional tests checking creation of an LB service in the charms that do it. I'd suggest creating a separate task for that though.
What do you think?

2023-01-23 13:55 UTC, gruyaume approved these changes
A couple of nitpicks but overall it's good

2023-01-23 13:55 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _on_fluentd_pebble_ready(self, event: PebbleReadyEvent):
```suggestion
    def _on_fluentd_pebble_ready(self, event: PebbleReadyEvent) -> None:
```

2023-01-23 13:55 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +        """Saves Fluentd certificate and CA certificate to the container.
It does a bit more than that (also pushes certs and config files to workload, configures pebble layer and puts charm to active)

2023-01-23 13:55 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _write_to_file(
I think `push_file_to_workload` would be a bit more precise

2023-01-23 14:12 UTC, ghislainbourgeois commented on .github/workflows/fluentd.yml
> +          /usr/bin/sg microk8s -c "microk8s kubectl -n kube-system rollout status deployment/hostpath-provisioner"
Ok, makes sense, we can discuss adding a task for checking the LB during planning.

2023-01-23 14:17 UTC, ghislainbourgeois approved these changes

2023-01-23 14:50 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._configure_and_start_workload()
There is a small issue here related to the ticket I am working on, we should restart the service after changing the config. If you feel this is too much for this PR, no problems, I will be adding the changes after this one is merged.

2023-01-23 14:59 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._configure_and_start_workload()
Not sure if that's what you mean, but `_configure_pebble_layer` restarts the workload service every time it's called:
```python
def _configure_pebble_layer(self) -> None:
    """Configures pebble layer."""
    pebble_layer = self._pebble_layer()
    plan = self._container.get_plan()
    if plan.services != pebble_layer.services:
        self._container.add_layer(self._container_name, pebble_layer, combine=True)
    self._container.restart(self._service_name)
    logger.info(f"Restarted container {self._service_name}")
```

2023-01-23 15:00 UTC, ghislainbourgeois commented on fluentd-elasticsearch-operator/src/charm.py
> +        self._configure_and_start_workload()
Yes, I read wrong, thanks!

2023-01-23 15:03 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _write_to_file(
Changed.

2023-01-23 15:03 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +        """Saves Fluentd certificate and CA certificate to the container.
True. Updated.

2023-01-23 15:04 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
> +    def _on_fluentd_pebble_ready(self, event: PebbleReadyEvent):
Done.

2023-01-23 15:45 UTC, merged