Fix: updating root certs in the relation data
canonical/charmed-magma-orchestrator pull request #147
Opened 2022-12-27 15:43 UTC by Gmerold

# Description

Fixes [TELCO-358](https://warthogs.atlassian.net/browse/TELCO-358)
Updates root certs (`rootCA.pem` and `controller.crt`) in the relation data after they are recreated.

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-20 22:42 UTC, ghislainbourgeois commented on orc8r-nginx-operator/src/charm.py
> +                self._kill_process(nginx_pid)
A simpler way to do this would be to send a signal to the master nginx process to reload its config. `kill -HUP $(cat /var/run/nginx.pid)`. This is simpler and should also have the advantage of being done gracefully.

2023-01-23 12:32 UTC, Gmerold commented on orc8r-nginx-operator/src/charm.py
> +                self._kill_process(nginx_pid)
Great idea! Thanks!
It works perfectly.

2023-01-23 14:26 UTC, ghislainbourgeois requested changes

2023-01-23 14:26 UTC, ghislainbourgeois commented on orc8r-nginx-operator/src/charm.py
> +        self._install_procps()
I don't think this is required anymore

2023-01-23 14:26 UTC, ghislainbourgeois commented on orc8r-nginx-operator/src/charm.py
> +
As above

2023-01-23 15:06 UTC, Gmerold commented on orc8r-nginx-operator/src/charm.py
> +        self._install_procps()
It actually is, because `procps` provides `kill`.

2023-01-23 16:06 UTC, ghislainbourgeois approved these changes

2023-01-24 14:00 UTC, gruyaume commented on nms-nginx-proxy-operator/src/charm.py
> +        # TODO: Replace the proxy_pass line content with data coming from the magmalte relation
Should we tackle this TODO here?

2023-01-24 14:00 UTC, gruyaume commented on nms-nginx-proxy-operator/src/charm.py
> +            "listen 443;\n"
This `443` should probably be a variable. It's referred to in the `KubernetesServicePatch` as well.

2023-01-24 14:00 UTC, gruyaume commented on nms-nginx-proxy-operator/src/charm.py
> +    def _write_nginx_config_file(self) -> None:
```suggestion
    def _push_nginx_config_file_to_workload(self) -> None:
```

2023-01-24 14:00 UTC, gruyaume commented on nms-nginx-proxy-operator/src/charm.py
> +        logger.info(f"Restarted container {self._service_name}")
It's not the container that's being restarted but the service right?

2023-01-24 14:42 UTC, Gmerold commented on nms-nginx-proxy-operator/src/charm.py
> +        # TODO: Replace the proxy_pass line content with data coming from the magmalte relation
I could do that, but it will require changes in the `nms-magmalte`, because currently it doesn't publish any information about the service it creates.

2023-01-24 14:45 UTC, Gmerold commented on nms-nginx-proxy-operator/src/charm.py
> +            "listen 443;\n"
Done.

2023-01-24 14:45 UTC, Gmerold commented on nms-nginx-proxy-operator/src/charm.py
> +    def _write_nginx_config_file(self) -> None:
Changed.

2023-01-24 14:45 UTC, Gmerold commented on nms-nginx-proxy-operator/src/charm.py
> +        logger.info(f"Restarted container {self._service_name}")
Changed.

2023-01-25 09:29 UTC, Gmerold commented on nms-nginx-proxy-operator/src/charm.py
> +        # TODO: Replace the proxy_pass line content with data coming from the magmalte relation
Done.

2023-01-27 15:11 UTC, ghislainbourgeois approved these changes
LGTM

2023-01-30 09:16 UTC, merged