Telco 384 update fluentd pem when certifier pem changes
canonical/charmed-magma-orchestrator pull request #168
Opened 2023-02-03 13:40 UTC by Gmerold

# Description

Updates `fluentd.pem` whenever `certifier.pem` changes.
`certifier.pem` is a CA signing the `fluentd.pem`.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-02-03 17:07 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +                )
Won't this constantly regenerate certificates for all `fluentd_relations` since the CSR stays in the relation data bag?

2023-02-03 18:21 UTC, gruyaume requested changes

2023-02-03 18:21 UTC, gruyaume commented on fluentd-elasticsearch-operator/src/charm.py
We should probably do this change in the new repo @sanchezfdezjavier created

2023-02-06 08:49 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +                )
Yes, you're right. Great catch!
I refactored this into two separate cases - one for certificate request being made by the new relation and another one for cases when certs need to be regenerated.

2023-02-06 08:51 UTC, Gmerold commented on fluentd-elasticsearch-operator/src/charm.py
It's already there.

2023-02-06 14:41 UTC, ghislainbourgeois approved these changes

2023-02-06 16:50 UTC, gruyaume approved these changes

2023-02-06 16:50 UTC, merged