Fixes dependencies for 1.6 release
canonical/charmed-magma-orchestrator pull request #173
Opened 2023-02-07 14:20 UTC by sanchezfdezjavier

# Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behavior of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-02-08 09:31 UTC, saltiyazan reviewed
We might need to fix the versions of packages installed by charmcraft.yaml too, no?

2023-02-08 09:34 UTC, saltiyazan commented on orc8r-base-acct-operator/tox.ini
> -
no version fixing needed here?

2023-02-08 09:42 UTC, saltiyazan commented on orc8r-base-acct-operator/tox.ini
> -
And requirements.txt is missing too for this charm

2023-02-08 09:46 UTC, sanchezfdezjavier commented on orc8r-base-acct-operator/tox.ini
> -
That charm is for Federation Gateway, which is not going to be in this release.

2023-02-08 10:10 UTC, Gmerold reviewed
What about the GH workflows? 
Shouldn't we also fix the versions there (i. e. `tox` version)?

2023-02-08 10:10 UTC, Gmerold commented on nms-magmalte-operator/tox.ini
>      black {[vars]all_path}
Is anyone actually using this? 
Perhaps we can just remove it?

2023-02-08 10:10 UTC, Gmerold commented on nms-magmalte-operator/tox.ini
>      coverage[toml]
What about this guy here?

2023-02-08 10:10 UTC, Gmerold commented on nms-nginx-proxy-operator/tox.ini
>      black {[vars]all_path}
As above. It actually applies to all the files.

2023-02-08 10:10 UTC, Gmerold commented on nms-nginx-proxy-operator/tox.ini
>      coverage[toml]
As above. Same applies to the rest of the files.

2023-02-08 10:54 UTC, Gmerold requested changes

2023-02-08 10:54 UTC, Gmerold commented on orc8r-tenants-operator/tox.ini
> -    mypy
Static analysis doesn't like removing `mypy` ;)

2023-02-08 15:29 UTC, saltiyazan commented
> What about the GH workflows? Shouldn't we also fix the versions there (i. e. `tox` version)?

I can tackle this in [this pr.](https://github.com/canonical/charmed-magma-orchestrator/pull/159)
Is that okay @sanchezfdezjavier ?

2023-02-08 16:21 UTC, ghislainbourgeois commented on nms-magmalte-operator/tox.ini
>      black {[vars]all_path}
I am not, it is directly configured in vim, not sure what the rest of the team is doing.

2023-02-08 16:25 UTC, ghislainbourgeois requested changes

2023-02-08 16:25 UTC, ghislainbourgeois commented on orc8r-metricsd-operator/tox.ini
> +    pytest==7.0.1
Instead of keeping all those versions up-to-date in each tox files, maybe we can have something like a `build-requirements.txt` that we could maintain instead? It would save us a lot of manual work.

2023-02-09 09:09 UTC, sanchezfdezjavier commented on orc8r-metricsd-operator/tox.ini
> +    pytest==7.0.1
I guess we mean global for all the charms, merging all the deps required by all the charms, is that correct?

2023-02-09 09:10 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tox.ini
>      black {[vars]all_path}
> > What about the GH workflows? Shouldn't we also fix the versions there (i. e. `tox` version)?
> 
> I can tackle this in [this pr.](https://github.com/canonical/charmed-magma-orchestrator/pull/159) Is that okay @sanchezfdezjavier ?

Sure, thanks!

2023-02-09 12:24 UTC, ghislainbourgeois commented on orc8r-metricsd-operator/tox.ini
> +    pytest==7.0.1
Yes, we use the same stuff all the time.

2023-02-09 18:26 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tox.ini
>      black {[vars]all_path}
I use it, but it can be removed if no one uses it.

2023-02-10 10:28 UTC, sanchezfdezjavier commented on nms-nginx-proxy-operator/tox.ini
>      coverage[toml]
Fixed.

2023-02-10 10:28 UTC, sanchezfdezjavier commented on orc8r-tenants-operator/tox.ini
> -    mypy
Fixed.

2023-02-10 10:29 UTC, sanchezfdezjavier commented on nms-nginx-proxy-operator/tox.ini
>      black {[vars]all_path}
Fixeld

2023-02-10 10:29 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tox.ini
>      coverage[toml]
Fixed.

2023-02-10 10:30 UTC, sanchezfdezjavier commented on orc8r-metricsd-operator/tox.ini
> +    pytest==7.0.1
Done.

2023-02-10 11:19 UTC, Gmerold approved these changes
LGTM

2023-02-10 13:46 UTC, ghislainbourgeois approved these changes
Just left a small nitpick, feel free to resolve and merge after

2023-02-10 13:46 UTC, ghislainbourgeois commented on orc8r-lte-operator/tox.ini
> +    coverage[toml]==7.0.1
```suggestion
    -r{toxinidir}/../test-requirements.txt
```

2023-02-13 09:07 UTC, saltiyazan approved these changes

2023-02-14 12:52 UTC, closed without merging