Fixes admin-operator and certifier.pem not being updated in relation …
canonical/charmed-magma-orchestrator pull request #176
Opened 2023-02-08 10:54 UTC by sanchezfdezjavier

# Description

Fixes admin-operator and certifier.pem not being updated in relation …

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-02-08 11:42 UTC, Gmerold requested changes

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
>                  self._regenerate_fluentd_certificates(event)
I don't think we should suppress `C901`.
You could extract this part to a separate method to reduce complexity of `_on_leader_config_changed`.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    def test_given_certificate_is_stored_with_no_relation_when_admin_operator_controller_certificate_request_then_certificate_is_set_in_admin_operator_lib(  # noqa: E501
Shouldn't it be `...then_runtime_error_is_raised`?

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    def test_given_admin_operator_certificate_when_certificate_is_regenerated_then_certificate_is_set_in_admin_operator_lib_for_each_relation(  # noqa: E501
This test checks what happens upon cert **request**, not **regeneration**. To test **regeneration**, you should first populate the relation data with whatever cert and key and then simulate `config_changed` causing certs to be regenerated.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +            )
One thing noticed by @ghislainbourgeois in my [my PR for Fluentd certs](https://github.com/canonical/charmed-magma-orchestrator/pull/168) is that this `for` will update all existing relations whenever new relation joins; and there's no need to update all the relations if the cert didn't change.
We might wanna have separate handling for each case.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +            )
Same as above.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    def test_given_admin_operator_certificate_when_certificate_is_regenerated_then_certificate_is_set_in_admin_operator_lib_for_each_relation(  # noqa: E501
Please also check the comment about updating multiple relations when the cert didn't change.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    def test_given_certifier_certificate_when_certificate_is_regenerated_then_certificate_is_set_in_cert_certifier_lib_for_each_relation(  # noqa: E501
As above - this test doesn't test **regeneration**.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        event.relation_id = cert_certifier_relation_id1
Do we need that?

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        event.relation_id = cert_admin_operator_relation_id1
Do we need that?

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self.harness.update_config(key_values={"domain": "whatever.com"})
If you want to trigger certs regeneration, the `domain` here needs to be different from the one used to generate initial certs.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +            admin_operator_certificate=False,
Why `false`? If that's `false`, you're not testing **regeneration**. 
What we want to check in **regeneration** scenario, is that the relation data bag is updated with the new certs when they're changed. In practice first you need to make sure some certs are in the `peer` relation data (by setting relevant params here to `True`), then you need to create a relation (charm will receive `certificate_requested` from the relation and will push the initial cert to the relation data bag) and finally you need to cause certs regeneration (config change) and check whether the new certs have been pushed to the relation data.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +            admin_operator_certificate=False,
As above.

2023-02-08 11:42 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self.harness.update_config(key_values={"domain": "whatever.com"})
As above.

2023-02-08 11:54 UTC, Gmerold commented
[Here's a post](https://stackoverflow.com/a/44836635) which will help you fix missing exec permissions on the `charm.py` files.

2023-02-08 11:56 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        "charms.magma_orc8r_certifier.v0.cert_admin_operator.CertAdminOperatorProvides.set_certificate"  # noqa: E501, W505
You don't need `noqa` here.

2023-02-08 12:11 UTC, saltiyazan commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.container_pebble_ready(container_name=service_name)
is the duplication here intended?

2023-02-08 12:23 UTC, saltiyazan commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +            patch_set_private_key.assert_called_with(
Shouldn't we emit the event instead of directly calling the private function?

2023-02-08 12:31 UTC, Gmerold commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.container_pebble_ready(container_name=service_name)
It is. I would add another assertion between them however (to make sure number of restarts increases).

2023-02-08 13:58 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.container_pebble_ready(container_name=service_name)
Yes, for this condition `if plan.services != layer.services:` in `_configure_pebble` to not be met.

2023-02-08 14:07 UTC, ghislainbourgeois requested changes

2023-02-08 14:07 UTC, ghislainbourgeois commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        # private_key = "whatever private key"
```suggestion
```

2023-02-08 14:07 UTC, saltiyazan commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.container_pebble_ready(container_name=service_name)
alright, thanks

2023-02-08 18:08 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/src/charm.py
> +            )
@ghislainbourgeois and I have been taking a look at this and we think If the relation data is not changed Juju won't trigger any relation changed event because the controller compares the new info with the existing one, even if we call the `set_certificate`. It's explained [here](https://juju.is/docs/sdk/relation-name-relation-changed-event) at the end.
>When is data synchronized? 
Relation data is sent to the controller at the end of the hook’s execution. If a charm author writes to local relation data multiple times during the a single hook run, the net change will be sent to the controller after the local code has finished executing. The controller inspects the data and determines whether the relation data has been changed. Related units then get the relation-changed event the next time they check in with the controller.

Let me know if that makes sense.

2023-02-08 18:09 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/src/charm.py
> +            )
Same here.

2023-02-08 18:09 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/src/charm.py
>                  self._regenerate_fluentd_certificates(event)
Fixed.

2023-02-08 18:09 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    def test_given_certificate_is_stored_with_no_relation_when_admin_operator_controller_certificate_request_then_certificate_is_set_in_admin_operator_lib(  # noqa: E501
Fixed and remove unused assert.

2023-02-08 18:17 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        event.relation_id = cert_certifier_relation_id1
No, removed.

2023-02-08 18:17 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        event.relation_id = cert_admin_operator_relation_id1
No, removed.

2023-02-08 18:17 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self.harness.update_config(key_values={"domain": "whatever.com"})
Fixed.

2023-02-08 18:17 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +            admin_operator_certificate=False,
Fixed.

2023-02-08 18:18 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +            admin_operator_certificate=False,
Fixed.

2023-02-08 18:18 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self.harness.update_config(key_values={"domain": "whatever.com"})
Fixed.

2023-02-08 18:18 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +            patch_set_private_key.assert_called_with(
Yes, fixed.

2023-02-08 18:18 UTC, sanchezfdezjavier commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        # private_key = "whatever private key"
Removed.

2023-02-08 18:44 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    def test_given_certifier_certificate_when_certificate_is_regenerated_then_certificate_is_set_in_cert_certifier_lib_for_each_relation(  # noqa: E501
Fixed.

2023-02-09 09:59 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> +            )
It does, yes.
Thanks.

2023-02-09 10:47 UTC, Gmerold commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        patch_connection_string,
These two are not used in the code. You can remove it, remove the corresponding patches. To make the test work after that, you'll just have to mock `container.exec`

2023-02-09 10:47 UTC, Gmerold commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.set_can_connect(container=container, val=True)
These two can be removed.

2023-02-09 10:47 UTC, Gmerold commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.assertEqual(plan, updated_plan)
Instead of doing multiple actions and check here, you could apply the pebble layer matching the one defined by the charm, fire `pebble_ready` and check whether the restart was called:
```python
test_pebble_layer = {STUFF FROM THE CHARM HERE}
self._container.add_layer(service_name, test_pebble_layer, combine=True)

self.harness.container_pebble_ready(container_name=service_name)

patch_container_restart.assert_called_once()
```

2023-02-09 10:47 UTC, Gmerold commented on orc8r-certifier-operator/src/charm.py
> -            self._push_application_certificates()
IMO this should stay where it was. I'd suggest:
```python
self._generate_application_certificates()
self._push_application_certificates()
self._update_certs_in_relations(event)
```

2023-02-09 10:47 UTC, Gmerold commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +
Check the comment about adding the expected plan explicitly.

2023-02-09 10:47 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self, patch_set_certificate, patch_pull, patch_push
`patch_push` is not used in the code.

2023-02-09 10:47 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        _, key_values = self.create_peer_relation_with_certificates(
```suggestion
        _, __ = self.create_peer_relation_with_certificates(
```

2023-02-09 10:47 UTC, Gmerold commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self, patch_set_certificate, patch_pull, patch_push
`patch_push` is not used in the code.

2023-02-09 10:47 UTC, Gmerold commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        self, patch_container_restart, patch_push, patch_exists
`patch_push` and `patch_exist` are not used in the code.

2023-02-09 10:47 UTC, Gmerold commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        self, patch_container_restart, patch_push, patch_exists
As above. You can do:
```python
@patch("ops.model.Container.exists", Mock())
@patch("ops.model.Container.push", Mock())
@patch("ops.model.Container.restart")
def test_given_no_change_in_pebble_plan_when_configure_pebble_then_container_is_restarted(
    self, patch_container_restart
```

2023-02-09 12:20 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        patch_connection_string,
Fixed.

2023-02-09 12:20 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self, patch_set_certificate, patch_pull, patch_push
Fixed.

2023-02-09 12:20 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        _, key_values = self.create_peer_relation_with_certificates(
Fixed.

2023-02-09 12:20 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +        self, patch_set_certificate, patch_pull, patch_push
Fixed.

2023-02-09 12:20 UTC, sanchezfdezjavier commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        self, patch_container_restart, patch_push, patch_exists
Fixed.

2023-02-09 12:20 UTC, sanchezfdezjavier commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +        self, patch_container_restart, patch_push, patch_exists
Thanks for the hint. Fixed.

2023-02-09 14:01 UTC, sanchezfdezjavier commented on orc8r-orchestrator-operator/tests/unit/test_charm.py
> +
Done.

2023-02-09 14:01 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/src/charm.py
> -            self._push_application_certificates()
Done.

2023-02-09 14:01 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.assertEqual(plan, updated_plan)
Thanks, done.

2023-02-09 14:01 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tests/unit/test_charm.py
> +        self.harness.set_can_connect(container=container, val=True)
Removed.

2023-02-09 15:28 UTC, ghislainbourgeois approved these changes

2023-02-09 16:11 UTC, Gmerold approved these changes
LGTM

2023-02-09 17:30 UTC, merged