Fixes the docs to reflect the 1.6 release
canonical/charmed-magma-orchestrator pull request #180
Opened 2023-02-10 11:54 UTC by saltiyazan

# Description

Fixes the docs to reflect the 1.6 release

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-02-10 12:07 UTC, sanchezfdezjavier commented on nms-magmalte-operator/README.md
> +juju deploy magma-nms-magmalte nms-magmalte --channel=1.6/stable
Should we set each individual charm to `1.6/stable`? I don't see any reason why someone would want to individually deploy charms in that track, if coming to this readme, it's probably because of bug/security fixes in `1.6/edge`, I'm not sure, let me know what you think.

2023-02-10 12:10 UTC, saltiyazan commented on nms-magmalte-operator/README.md
> +juju deploy magma-nms-magmalte nms-magmalte --channel=1.6/stable
Is it the `stable` part you don't agree with?
In my opinion, it's not accurate to leave the documents on the 1.6 release without adding the 1.6 channel.

2023-02-10 12:22 UTC, Gmerold commented on nms-magmalte-operator/README.md
> +juju deploy magma-nms-magmalte nms-magmalte --channel=1.6/stable
I think we actually **should** point to **stable** in case of branches. IMO, one of the main purposes of doing branches is to show the world we have something that is working; and **stable** will have the most... _stable_ version of our software. If there are any bug/security fixes in the released branch, we should deliver them, make sure they're properly tested and push them to **stable** asap.

2023-02-10 12:46 UTC, Gmerold approved these changes
Nitpicking ;)

2023-02-10 12:46 UTC, Gmerold commented on nms-nginx-proxy-operator/README.md
> +juju deploy magma-nms-magmalte nms-magmalte  --channel=1.6/stable
```suggestion
juju deploy magma-nms-magmalte nms-magmalte --channel=1.6/stable
```

2023-02-10 12:46 UTC, Gmerold commented on nms-nginx-proxy-operator/README.md
> +juju deploy magma-orc8r-certifier --config domain=<your domain> orc8r-certifier  --channel=1.6/stable
```suggestion
juju deploy magma-orc8r-certifier --config domain=<your domain> orc8r-certifier --channel=1.6/stable
```

2023-02-10 12:46 UTC, Gmerold commented on orc8r-accessd-operator/README.md
> +juju deploy magma-orc8r-accessd orc8r-accessd  --channel=1.6/stable
```suggestion
juju deploy magma-orc8r-accessd orc8r-accessd --channel=1.6/stable
```

2023-02-10 12:46 UTC, Gmerold commented on orc8r-analytics-operator/README.md
> +juju deploy magma-orc8r-analytics orc8r-analytics  --channel=1.6/stable
```suggestion
juju deploy magma-orc8r-analytics orc8r-analytics --channel=1.6/stable
```

2023-02-10 12:46 UTC, gruyaume requested changes
Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden

2023-02-10 12:46 UTC, gruyaume commented on orc8r-accessd-operator/README.md
> +juju deploy magma-orc8r-accessd orc8r-accessd  --channel=1.6/stable
I wouldn't bother with all the individual readme's. I don't think we want to update them with every release, specially knowing that literally nobody will read them.

2023-02-10 12:46 UTC, gruyaume commented on README.md
> +## Charmed Magma Orchestrator - Release 1.6
I don't think we want this here. In the `charmed-magma` docs [here](https://canonical.github.io/charmed-magma/main/how-to/deploy_charmed_magma_orchestrator/) you may want to update the juju version, Kubernetes version to be those here but that's about it.

2023-02-10 12:49 UTC, Gmerold commented
> Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden

Isn't the default `latest`?

2023-02-10 13:16 UTC, saltiyazan commented
> Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden

I see your point, and I agree that it's an extra burden to do it for every release.
I only can repeat myself here saying that it will make the individual readmes inaccurate.
If you go to branch 1.6 and run the command that is in the readme, you won't actually get the 1.6 version.

2023-02-10 13:46 UTC, saltiyazan commented on README.md
> +## Charmed Magma Orchestrator - Release 1.6
Removed.

2023-02-10 13:48 UTC, gruyaume commented
> > Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden
> 
> Isn't the default `latest`?

The default is `latest/stable` right? Until we have 1.8 released that would point to `1.6/stable` I assume.

2023-02-10 13:50 UTC, gruyaume commented
> > Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden
> 
> I see your point, and I agree that it's an extra burden to do it for every release. I only can repeat myself here saying that it will make the individual readmes inaccurate. If you go to branch 1.6 and run the command that is in the readme, you won't actually get the 1.6 version.

Then we can simply change the root README.md but more importantly the charmed-magma mkdocs documentation to specify the `1.6/latest` but I wouldn't put it in all individual charms.

2023-02-10 13:51 UTC, saltiyazan commented
> > > Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden
> > 
> > 
> > I see your point, and I agree that it's an extra burden to do it for every release. I only can repeat myself here saying that it will make the individual readmes inaccurate. If you go to branch 1.6 and run the command that is in the readme, you won't actually get the 1.6 version.
> 
> Then we can simply change the root README.md but more importantly the charmed-magma mkdocs documentation to specify the `1.6/latest` but I wouldn't put it in all individual charms.

Alright, I'll remove the individual files and keep the root one.

2023-02-10 13:51 UTC, ghislainbourgeois approved these changes

2023-02-10 13:52 UTC, Gmerold commented
> > > Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden
> > 
> > 
> > Isn't the default `latest`?
> 
> The default is `latest/stable` right? Until we have 1.8 released that would point to `1.6/stable` I assume.

Yes, but we push to `latest` track from the `main` branch. I'm not sure if it will fallback to `1.6/stable`.

2023-02-10 13:54 UTC, sanchezfdezjavier commented on nms-magmalte-operator/README.md
> +juju deploy magma-nms-magmalte nms-magmalte --channel=1.6/stable
Makes sense, I agree.

2023-02-10 13:57 UTC, gruyaume commented
> > > > Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden
> > > 
> > > 
> > > Isn't the default `latest`?
> > 
> > 
> > The default is `latest/stable` right? Until we have 1.8 released that would point to `1.6/stable` I assume.
> 
> Yes, but we push to `latest` track from the `main` branch. I'm not sure if it will fallback to `1.6/stable`.

We publish the content of `main` to `latest/edge`, not `latest/stable`. Ultimately we'll have to see, we may have to add something to point `latest/stable` to whatever our latest release is, in this case `1.6/stable`

2023-02-14 13:31 UTC, Gmerold approved these changes

2023-02-14 13:44 UTC, Gmerold approved these changes

2023-02-14 13:44 UTC, saltiyazan commented
> > > Overall I don't see the value of this PR. When people will deploy `juju deploy magma-orc8r`, it will automatically point to this new branch. In the documentation it will also show `1.6` in the top of the page. Overall I believe this is enough and that there is no need to be more specific than that. Everything that we are adding here is stuff that we would have to add at any release. It's a bit of a burden
> > 
> > 
> > I see your point, and I agree that it's an extra burden to do it for every release. I only can repeat myself here saying that it will make the individual readmes inaccurate. If you go to branch 1.6 and run the command that is in the readme, you won't actually get the 1.6 version.
> 
> Then we can simply change the root README.md but more importantly the charmed-magma mkdocs documentation to specify the `1.6/latest` but I wouldn't put it in all individual charms.

Alright, that's done.
Could you please take a quick look @gruyaume ?

2023-02-16 16:03 UTC, gruyaume approved these changes

2023-02-17 08:14 UTC, merged