Fix render bundle
canonical/charmed-magma-orchestrator pull request #184
Opened 2023-02-14 10:36 UTC by saltiyazan

# Description

Fix render bundle and bundle template to support tracks.

## Checklist

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-02-14 12:47 UTC, ghislainbourgeois approved these changes

2023-02-14 12:48 UTC, Gmerold requested changes

2023-02-14 12:48 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
`local` can't be true anymore, because the charm has been moved to a separate repo.

2023-02-14 12:48 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
As above - it can't be `local`.
Also, in the release branch, don't we want external charms to be always taken from `latest/stable` (default)?

2023-02-14 12:48 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
> +    channel: {{ track|default("latest") }}/{{ channel|default("edge") }}
Do we want to keep latest as a default? Wouldn't `1.6` be better?

2023-02-14 12:48 UTC, Gmerold commented on orc8r-bundle/render_bundle.py
> +    parser.add_argument(
Do we need this? Is there any use case for using `latest` in the release branch?

2023-02-14 12:48 UTC, Gmerold commented on orc8r-bundle/tests/unit/expected_bundles/charmhub_edge.yaml
> +    charm: fluentd-elasticsearch
```suggestion
    charm: fluentd-elasticsearch
```

2023-02-14 12:48 UTC, Gmerold commented on orc8r-bundle/tests/unit/expected_bundles/charmhub_edge.yaml
> +    channel: latest/edge
```suggestion
    channel: 1.6/edge
```
?

2023-02-14 12:53 UTC, sanchezfdezjavier commented on orc8r-bundle/tests/unit/expected_bundles/charmhub_edge.yaml
> +    charm: fluentd-elasticsearch
```suggestion
    charm: fluentd-elasticsearch
```

2023-02-14 12:58 UTC, saltiyazan commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
You are right.
However I think the condition applies here too.
If we want to render a local bundle we will use the edge channel. This was the behaviour so far. (some charms won't be magma specific and won't be local)

2023-02-14 12:59 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
For the release branch, I'm not sure if we wanna use external charms from edge?

2023-02-14 13:02 UTC, saltiyazan commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
As above.
The mistake here probably is that this pr is targeting 1.6 while it should target main.
And then keep the template and the render script common, and modify the actions to use it as it is fit.
I will change the base.

2023-02-14 13:04 UTC, sanchezfdezjavier commented on orc8r-bundle/tests/unit/expected_bundles/local.yaml
> +    charm: ./magma-nms-nginx-proxy_ubuntu-22.04-amd64.charm
Is there any reason for this change?

2023-02-14 13:05 UTC, Gmerold commented on orc8r-bundle/tests/unit/expected_bundles/local.yaml
> +    charm: ./magma-nms-nginx-proxy_ubuntu-22.04-amd64.charm
This charm uses rock and Ubuntu 22.04 as a base.

2023-02-14 13:06 UTC, saltiyazan commented on orc8r-bundle/tests/unit/expected_bundles/local.yaml
> +    charm: ./magma-nms-nginx-proxy_ubuntu-22.04-amd64.charm
That's how it is in the bundle.
It probably was changed in a previous prs and the unit tests were not synced to it :)

2023-02-14 13:08 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
So it's the same thing we've had with the workflows - do we wanna add `if`s to handle branches? Or do we make it release `1.6` specific as this file is in the branch anyway?

2023-02-14 13:10 UTC, sanchezfdezjavier commented on orc8r-bundle/tests/unit/expected_bundles/charmhub_edge.yaml
> +    charm: fluentd-elasticsearch
Duplicated with Bart's comment. Resolved.

2023-02-14 13:43 UTC, sanchezfdezjavier commented on orc8r-bundle/tests/unit/expected_bundles/local.yaml
> +    charm: ./magma-nms-nginx-proxy_ubuntu-22.04-amd64.charm
Thanks, resolved.

2023-02-15 06:33 UTC, saltiyazan commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
Fixed, external charms will be from stable.

2023-02-15 06:34 UTC, saltiyazan commented on orc8r-bundle/bundle.yaml.j2
> +    {%- if track == 'latest' or local == true %}
Changed to be release specific. ✅

2023-02-15 06:34 UTC, saltiyazan commented on orc8r-bundle/bundle.yaml.j2
> +    channel: {{ track|default("latest") }}/{{ channel|default("edge") }}
default for this branch will be 1.6/stable. Fixed.

2023-02-15 06:35 UTC, saltiyazan commented on orc8r-bundle/render_bundle.py
> +    parser.add_argument(
Fixed.

2023-02-15 06:35 UTC, saltiyazan commented on orc8r-bundle/tests/unit/expected_bundles/charmhub_edge.yaml
> +    charm: fluentd-elasticsearch
✅

2023-02-15 06:35 UTC, saltiyazan commented on orc8r-bundle/tests/unit/expected_bundles/charmhub_edge.yaml
> +    channel: latest/edge
✅

2023-02-15 07:34 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
>        magma-nms-nginx-proxy-image: nginx:latest
```suggestion
      magma-nms-nginx-proxy-image: ghcr.io/canonical/nginx:1.23.3
```

2023-02-15 07:34 UTC, Gmerold commented on orc8r-bundle/bundle.yaml.j2
> +    channel: stable
Nitpicking, but stable is default, so you could just remove it.

2023-02-15 07:55 UTC, Gmerold approved these changes

2023-02-15 07:56 UTC, saltiyazan commented on orc8r-bundle/bundle.yaml.j2
> +    channel: stable
I'd say let's keep it as an informative label :)

2023-02-15 09:12 UTC, merged