Improves current how-to guides and adds GKE documentation
canonical/charmed-magma-orchestrator pull request #20
Opened 2022-03-03 11:34 UTC by gruyaume

- Converts current documentation to how-to guide following `how-to` best practices
- Adds GCP GKE documentation

2022-03-08 07:28 UTC, Gmerold requested changes
BTW, you might wanna run new docs through [markdown formatter](https://codebeautify.org/markdown-formatter) @sanchezfdezjavier proposed the other day to make them look consistent.

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +      gui-y: "300"
Do we need this? We're not using GUI anyway, right?

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +To configure Route53, on your Ubuntu machine go to the `documentation/how-to-guides/utils/route53_integrator` directory and run:
Shouldn't we mention that **charmed-magma** repo needs to be checked out prior to this step?

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +Add the relevant certificate as an admin user to the controller:
How about simply "Create Orchestrator admin user"?
Seems to resonate better with the action name.

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_eks.md
> +Add the relevant certificate as an admin user to the controller:
As above.

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_eks.md
> +To configure Route53, on your Ubuntu machine go to the `documentation/how-to-guides/utils/route53_integrator` directory and run:
As above.

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_gcp_gke.md
> +[here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html)).
GCP stuff would probably work better ;)

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_gcp_gke.md
> +Add the relevant certificate as an admin user to the controller:
As above.

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_microk8s.md
> +- Ubuntu 20.04 machine
Shouldn't we mention HW requirements (even roughly estimated) here?

2022-03-08 07:28 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_microk8s.md
> +Add the relevant certificate as an admin user to the controller:
As above.

2022-03-08 07:53 UTC, sanchezfdezjavier commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +- [eksctl](https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html)
Why do we need `eksctl` if we're using `charmed-kubernetes`?

2022-03-08 23:45 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_microk8s.md
> +- Ubuntu 20.04 machine
I think I would agree but
1. I'm not certain this should be included in the `how-to` guide
2. I truly don't know what are the hw requirements

2022-03-08 23:50 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +Add the relevant certificate as an admin user to the controller:
Agreed, fixed

2022-03-08 23:50 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +To configure Route53, on your Ubuntu machine go to the `documentation/how-to-guides/utils/route53_integrator` directory and run:
Agreed, fixed

2022-03-08 23:50 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +      gui-y: "300"
Agreed, fixed

2022-03-08 23:50 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_eks.md
> +To configure Route53, on your Ubuntu machine go to the `documentation/how-to-guides/utils/route53_integrator` directory and run:
Agreed, fixed

2022-03-08 23:50 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_gcp_gke.md
> +[here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html)).
Agreed, fixed

2022-03-08 23:51 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_gcp_gke.md
> +Add the relevant certificate as an admin user to the controller:
Agreed, fixed

2022-03-08 23:51 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_microk8s.md
> +Add the relevant certificate as an admin user to the controller:
Agreed, fixed

2022-03-08 23:51 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_charmed_kubernetes.md
> +- [eksctl](https://docs.aws.amazon.com/eks/latest/userguide/eksctl.html)
Agreed, fixed

2022-03-08 23:51 UTC, gruyaume commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_eks.md
> +Add the relevant certificate as an admin user to the controller:
Agreed, fixed

2022-03-08 23:56 UTC, gruyaume commented
@Gmerold Just passed the doc through the markdown formatter

2022-03-09 07:49 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_microk8s.md
> +- Ubuntu 20.04 machine
From what I understood from our session with Daniele, it should be ok to put this kind of info here. It's not an explanation or anything like that. The main purpose of having such information, would be to ensure user doesn't try to deploy our stuff on some 1 vCPU 1 GB RAM machine.
In the nearest future I'll probably be doing some deployments, so I'll try to figure out what would be the minimal VM spec; at least roughly. Then we can add this info.

2022-03-09 07:49 UTC, Gmerold approved these changes

2022-03-09 09:11 UTC, Gmerold requested changes

2022-03-09 09:11 UTC, Gmerold commented on orchestrator-bundle/documentation/how-to-guides/deploy_on_aws_eks.md
> +python3 route53_integrator --hosted_zone=<your domain> --namespace <your model>
This actually fails with 
`python3: can't open file 'route53_integrator': [Errno 2] No such file or directory`
since the main file in the given directory is called **main.py**

2022-03-09 19:06 UTC, closed without merging