Uses Magma 1.8
canonical/charmed-magma-orchestrator pull request #217
Opened 2023-02-27 10:32 UTC by saltiyazan

# Description

- Uses container images from Magma 1.8
- Adds ports that are required in 1.8
- Adds new relations
- Adds storage where required
- Uses new main organisation name in nms-magmalte
- Adds rootca to bootstrapper
- Modifies startup commands

## Checklist

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [x] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-03-08 12:50 UTC, Gmerold requested changes

2023-03-08 12:50 UTC, Gmerold commented on orc8r-accessd-operator/metadata.yaml
> +    minimum-size: 1M
Do we need it here? I don't see any new charm code which would make use of it.

2023-03-08 12:50 UTC, Gmerold commented on orc8r-bootstrapper-operator/metadata.yaml
> +        location: /var/opt/magma/configs/orc8r
Do we need this?

2023-03-08 12:50 UTC, Gmerold commented on orc8r-bootstrapper-operator/metadata.yaml
> +    minimum-size: 1M
As above.

2023-03-08 12:50 UTC, Gmerold commented on orc8r-bootstrapper-operator/README.md
> +Default: ghcr.io/canonical/magma-orc8r-controller:1.8.0
Not related to this line, but the whole README could use some update :)
It should reflect the fact that the bootstrapper needs the DB now, also we should specify the relation name for `juju relate`. `Requires` section should be updated too.

2023-03-08 12:50 UTC, Gmerold commented on orc8r-bundle/tests/unit/expected_bundles/local.yaml
> +      magma-orc8r-bootstrapper-image: ghcr.io/canonical/magma-orc8r-controller:1.8.0
What about new relations required by the bootstrapper?

2023-03-08 14:59 UTC, saltiyazan commented on orc8r-accessd-operator/metadata.yaml
> +    minimum-size: 1M
Removed.

2023-03-08 14:59 UTC, saltiyazan commented on orc8r-bootstrapper-operator/metadata.yaml
> +        location: /var/opt/magma/configs/orc8r
Removed.

2023-03-08 14:59 UTC, saltiyazan commented on orc8r-bootstrapper-operator/metadata.yaml
> +    minimum-size: 1M
Removed.

2023-03-08 14:59 UTC, saltiyazan commented on orc8r-bundle/tests/unit/expected_bundles/local.yaml
> +      magma-orc8r-bootstrapper-image: ghcr.io/canonical/magma-orc8r-controller:1.8.0
Done.

2023-03-08 14:59 UTC, saltiyazan commented on orc8r-bootstrapper-operator/README.md
> +Default: ghcr.io/canonical/magma-orc8r-controller:1.8.0
✅

2023-03-09 00:23 UTC, ghislainbourgeois requested changes

2023-03-09 00:23 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +pgsql = ops.lib.use("pgsql", 1, "postgresql-charmers@lists.launchpad.net")
This is a deprecated call, is it possible to import the lib directly?

2023-03-09 00:23 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +        return None
`Path.rglob()` would be a cleaner solution for this: https://docs.python.org/3/library/pathlib.html#pathlib.Path.rglob

2023-03-09 07:16 UTC, Gmerold commented on orc8r-bootstrapper-operator/README.md
>  juju relate orc8r-bootstrapper orc8r-certifier
This relation was actually never needed and can be removed.

2023-03-09 07:16 UTC, Gmerold commented on orc8r-bootstrapper-operator/README.md
> +juju relate orc8r-bootstrapper postgresql-k8s:db
It used to be a convention that if a charm requires other charms to work, we would mention deploy and relate commands for all of them; just to provide a ready solution for a working setup. I see it's been kinda neglected, but I think it's worth doing that. WDYT?

2023-03-09 07:16 UTC, Gmerold commented on orc8r-bootstrapper-operator/README.md
>  - **cert-bootstrapper**: Relation that provides the bootstrapper private key.
Private key is generated by the charm internally. There's nothing that provides it.

2023-03-09 08:07 UTC, saltiyazan commented on orc8r-bootstrapper-operator/src/charm.py
> +pgsql = ops.lib.use("pgsql", 1, "postgresql-charmers@lists.launchpad.net")
This [lib here](https://github.com/canonical/postgresql-k8s-operator/tree/main/lib/charms/postgresql_k8s/v0) that can be imported directly has a different interface :)
I know we plan to use this library. But for now to use the same like in other charms I went with this call.
Let me know if you don't agree :)

2023-03-09 08:50 UTC, saltiyazan commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +        return None
✅

2023-03-09 08:50 UTC, saltiyazan commented on orc8r-bootstrapper-operator/README.md
>  juju relate orc8r-bootstrapper orc8r-certifier
Done

2023-03-09 08:50 UTC, saltiyazan commented on orc8r-bootstrapper-operator/README.md
>  - **cert-bootstrapper**: Relation that provides the bootstrapper private key.
Done.

2023-03-09 09:04 UTC, saltiyazan commented on orc8r-bootstrapper-operator/README.md
> +juju relate orc8r-bootstrapper postgresql-k8s:db
Done.
I modified the README in orc8r-nginx too, to follow that.

2023-03-09 09:13 UTC, Gmerold approved these changes

2023-03-09 15:06 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +pgsql = ops.lib.use("pgsql", 1, "postgresql-charmers@lists.launchpad.net")
OK, that is fine

2023-03-09 15:19 UTC, ghislainbourgeois requested changes

2023-03-09 15:19 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +        return None
```suggestion
        if path := Path(charm_dir).rglob(charm_file_name):
            return str(path[0])
        return None
```

Small nitpick

2023-03-14 10:28 UTC, saltiyazan commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +        return None
the function returns a generator object that we can't index. and if I use `next` directly on it, there is a chance of gettin `StopIteration` exception.
I solved as follows:
`def _find_charm(charm_dir: str, charm_file_name: str) -> Optional[str]:
        try:
            path = next(Path(charm_dir).rglob(charm_file_name))
            return str(path)
        except StopIteration:
            return None`
 Please take a look and let me know.

2023-03-14 13:52 UTC, ghislainbourgeois approved these changes

2023-03-14 19:39 UTC, merged