Extracts integration charm deployments to an integration utils file
canonical/charmed-magma-orchestrator pull request #239
Opened 2023-04-10 09:49 UTC by saltiyazan

# Description

Many integration tests require the deployment of dependent charms, this is duplicated in integration test files, the goal of this PR is to extract that common logic into one utils file.

## Checklist

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [x] I validated that new and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-04-12 11:49 UTC, Gmerold commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            integration_utils.DB_APPLICATION_NAME, block_until_done=True, force=True
Not sure why, but to me, `integration_utils.DB_APPLICATION_NAME` looks kinda awkward. And, since we're not using `remove_application` for anything else in our tests, how about moving this whole block to a function in `integration_utils`? Then the test would be something like:
```python
await integration_utils.remove_postgresql(ops_test)
await ops_test.model.wait_for_idle(apps=[APPLICATION_NAME], status="blocked", timeout=1000)
```

2023-04-12 11:49 UTC, Gmerold commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=integration_utils.CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:db"
Same as above. It's a common integration, so maybe we could have a separate function for that and eliminate getting constants from `integration_utils`?

2023-05-02 06:34 UTC, saltiyazan commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            integration_utils.DB_APPLICATION_NAME, block_until_done=True, force=True
Done

2023-05-02 06:34 UTC, saltiyazan commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=integration_utils.CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:db"
Done

2023-05-02 06:48 UTC, ghislainbourgeois requested changes

2023-05-02 06:48 UTC, ghislainbourgeois commented on shared_test_utils/integration_constatns.py
The name of the file has a typo in it.

2023-05-02 06:48 UTC, ghislainbourgeois commented on shared_test_utils/integration_test_utils.py
> +from integration_constatns import *
This import also has the typo in it.

2023-05-02 06:48 UTC, ghislainbourgeois commented on shared_test_utils/integration_test_utils.py
> +async def deploy_tls_certificates_operator(ops_test):
I think the linting might not be running properly on this file, it usually complains that 2 blank lines are required at this level.

2023-05-02 07:15 UTC, sanchezfdezjavier requested changes

2023-05-02 07:15 UTC, sanchezfdezjavier commented on shared_test_utils/integration_test_utils.py
> +async def deploy_postgresql(ops_test):
We should add a parameter for the channel. For freezing at release time, and right now we're deploying from `14/stable` for using the new postgres lib.
```suggestion
async def deploy_postgresql(ops_test, channel="edge"):
```

2023-05-02 07:15 UTC, sanchezfdezjavier commented on shared_test_utils/integration_test_utils.py
> +async def deploy_postgresql(ops_test):
And we might want to do so for every charm, for the time of the release it would be handy.

We coud have a dict/yaml mapping charms to channels, used for populating both the bundle and itests. This way at release time, it would be only a matter of modifying this file. Just a quick idea.

2023-05-02 08:11 UTC, saltiyazan commented on shared_test_utils/integration_constatns.py
Fixed

2023-05-02 08:11 UTC, saltiyazan commented on shared_test_utils/integration_test_utils.py
> +from integration_constatns import *
Fixed

2023-05-02 08:22 UTC, ghislainbourgeois commented on shared-test-utils/integration_test_utils.egg-info/PKG-INFO
This whole `egg-info` directory should not be committed.

2023-05-02 08:56 UTC, saltiyazan commented on shared-test-utils/integration_test_utils.egg-info/PKG-INFO
my bad.
Removed.

2023-05-02 09:25 UTC, saltiyazan commented on shared_test_utils/integration_test_utils.py
> +async def deploy_tls_certificates_operator(ops_test):
I added tox and workflow files.

2023-05-02 09:42 UTC, saltiyazan commented on shared_test_utils/integration_test_utils.py
> +async def deploy_postgresql(ops_test):
We don't need to specify any channel for `orc8r` charms because they are always built from the current branch, in any case, release branch or not.
For external charms, when no channel is specified, then `latest/stable` is used, which is the case with releases `1.8` and `1.6`, I updated the utils file to match that behaviour.
Done.

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +async def deploy_tls_certificates_operator(ops_test, channel="latest/stable"):
Please add typing and update the docstring. 
It actually applies to most functions here.

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
Is E501 actually needed here?

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        relation2="postgresql-k8s:db",
When deploying the DB, we set the app name taken from the constant. I think it would make sense to use the same constant here.

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        relation2="postgresql-k8s:db",
Actually what do you think about extracting all apps names to contants?

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
Do we need E501 here?

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
As above.

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
Same :)

2023-05-02 10:16 UTC, Gmerold commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
And here

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +async def deploy_tls_certificates_operator(ops_test, channel="latest/stable"):
Done

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
No, fixed.

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +        relation2="postgresql-k8s:db",
Done

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-02 13:31 UTC, saltiyazan commented on shared-test-utils/src/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-04 12:19 UTC, ghislainbourgeois requested changes

2023-05-04 12:19 UTC, ghislainbourgeois commented on shared-test-utils/isort
Do we need this file?

2023-05-04 12:19 UTC, ghislainbourgeois commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +                relation2=f"{itest_const.DB_CHARM_NAME}:db",
The endpoint of that relation will change to `database` in all the charm, but not at the same time, maybe we should wait to merge this until all the libs update are done?

2023-05-04 12:19 UTC, ghislainbourgeois commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
This will need to change to `database`

2023-05-04 12:19 UTC, ghislainbourgeois commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
This will need to change to `database`.

2023-05-04 12:19 UTC, ghislainbourgeois commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
This will need to change to `database`.

2023-05-04 12:19 UTC, ghislainbourgeois commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
This will need to change to `database`.

2023-05-04 12:20 UTC, saltiyazan commented on shared-test-utils/isort
we don't. The file is not there :)

2023-05-05 12:05 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
✅

2023-05-05 12:05 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
✅

2023-05-05 12:05 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        relation2=f"{itest_const.DB_CHARM_NAME}:db",
✅

2023-05-05 12:05 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +                relation2=f"{itest_const.DB_CHARM_NAME}:db",
rebased!
✅

2023-05-05 12:46 UTC, ghislainbourgeois approved these changes
LGTM

2023-05-10 14:34 UTC, gruyaume approved these changes
Good job!

2023-05-10 14:34 UTC, gruyaume commented on nms-magmalte-operator/tests/integration/test_integration.py
> +        await integration_utils.deploy_grafana_k8s_operator(ops_test, channel="edge")
Unrelated to this PR but we should probably not use the `edge` version of grafana and other dependencies in our tests. This increases flakiness.

2023-05-16 11:13 UTC, Gmerold approved these changes

2023-05-16 17:19 UTC, sanchezfdezjavier commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +async def deploy_orc8r_certifier(ops_test) -> None:
Some docstrings in this file specify types, however we're not implementing type hints. Is there any reason we're not adding those?

2023-05-16 17:24 UTC, sanchezfdezjavier commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        series="jammy",
Do we want to hardcode the series? How about passing it as a parameter as we do with the channel in line `119`?

2023-05-16 17:25 UTC, sanchezfdezjavier commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        )  # noqa: E501
Do we need this ignore?

2023-05-16 17:27 UTC, sanchezfdezjavier commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +    """Deploys "prometheus-edge-hub" charm.
I would remove this just for consistency across docstrings.
```suggestion
    """Deploys prometheus-edge-hub charm.
```

2023-05-16 17:28 UTC, sanchezfdezjavier commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        )  # noqa: E501
Do we need this ignore?

2023-05-16 17:29 UTC, sanchezfdezjavier commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        )  # noqa: E501
Do we need this ignore?

2023-05-16 17:34 UTC, sanchezfdezjavier approved these changes
Feel free to resolve the comments after the nitpicking. Pretty cool to remove lots of repeated code! 🎉

2023-05-17 10:01 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-17 10:01 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +    """Deploys "prometheus-edge-hub" charm.
✅

2023-05-17 10:01 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-17 10:02 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +        )  # noqa: E501
✅

2023-05-17 10:02 UTC, saltiyazan commented on shared_test_utils/src/integration_test_utils/integration_test_utils.py
> +async def deploy_orc8r_certifier(ops_test) -> None:
added except for ops_test.

2023-05-17 13:03 UTC, merged