Fixes version of lxd in project
canonical/charmed-magma-orchestrator pull request #249
Opened 2023-04-18 10:43 UTC by saltiyazan

# Description

LXD doesn't have a 5.10/stable version anymore, this pr pumps the version of lxd to 5.11/stable

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-04-18 11:32 UTC, gruyaume approved these changes

2023-04-18 13:05 UTC, ghislainbourgeois approved these changes

2023-04-19 14:32 UTC, Gmerold requested changes

2023-04-19 14:32 UTC, Gmerold commented on .github/variables/dependencies_versions.env
>  JUJU_VERSION=3.1/stable
`3.1/stable` in release `1.6`? Are you sure you've branched off the right branch?

2023-04-20 08:20 UTC, saltiyazan commented on .github/variables/dependencies_versions.env
>  JUJU_VERSION=3.1/stable
Nice catch, I wonder how didn't github diff find it.
Thanks.
It's fixed now.

2023-04-20 13:08 UTC, Gmerold reviewed
Looks like `psycopg2-binary` 2.9.5 stopped working (failing itests) after the new version has been released. I've checked locally with 2.9.6 and it works. I guess we need to bump the version.

2023-04-25 07:47 UTC, Gmerold approved these changes

2023-04-25 08:41 UTC, merged