Uses new data platform lib bootstrapper
canonical/charmed-magma-orchestrator pull request #253
Opened 2023-04-21 10:28 UTC by sanchezfdezjavier

# Description

Uses new data platform lib in `orc8r-bootstrapper`.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-04-21 19:30 UTC, ghislainbourgeois approved these changes
Small nitpick, otherwise, LGTM

2023-04-21 19:30 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +                            "DATABASE_SOURCE": f"dbname={self.DB_NAME} "  # type: ignore[union-attr] # noqa: E501
I am pretty sure that `# noqa: E501` is unnecessary.

2023-04-22 10:01 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/src/charm.py
> +                            "DATABASE_SOURCE": f"dbname={self.DB_NAME} "  # type: ignore[union-attr] # noqa: E501
If I remove it I get `/Users/javi/charmed-magma-orchestrator/orc8r-bootstrapper-operator/src/charm.py:95:100: E501 line too long (100 > 99 characters)`. The line without the noqa is exactly 100, I might be missing something.

2023-04-24 10:01 UTC, gruyaume approved these changes

2023-04-24 10:02 UTC, ghislainbourgeois requested changes

2023-04-24 10:02 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/metadata.yaml
> +    interface: postgresql_client
Need to update the bundle as well

2023-04-24 10:16 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/metadata.yaml
> +    interface: postgresql_client
Done.

2023-04-25 10:19 UTC, ghislainbourgeois requested changes

2023-04-25 10:19 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +                "host": relation_data["endpoints"],
I found a bug with this today, this will need to be changed to something like:
```suggestion
                "host": relation_data["endpoints"].split(":")[0],
                "port": relation_data["endpoints"].split(":")[1].split(",")[0],
```

2023-04-25 10:26 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/src/charm.py
> +                "host": relation_data["endpoints"],
Fixed.

2023-04-25 10:30 UTC, ghislainbourgeois requested changes

2023-04-25 10:30 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +        # self.framework.observe(self.on.db_relation_broken, self._on_database_relation_broken)
This will need to be fixed before merging.

2023-04-25 10:30 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +                "host": relation_data["endpoints"].split(":")[0],
You are still missing the port

2023-04-25 10:30 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2=f"{DB_APPLICATION_NAME}:database"
The certifier is not yet updated to the new lib, so should still use `db`.

2023-04-25 12:50 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/src/charm.py
> +        # self.framework.observe(self.on.db_relation_broken, self._on_database_relation_broken)
Done.

2023-04-25 12:53 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/src/charm.py
> +                "host": relation_data["endpoints"].split(":")[0],
True. I've spot an issue in our tests, we were patching `@patch("charm.ConnectionString")` ` patch_connection_string.return_value = self.TEST_DB_CONNECTION_STRING` in `test_given_private_key_is_stored_when_pebble_ready_then_pebble_plan_is_filled_with_workload_service_content` so we weren't testing our actual but, just hardcoding the expected result! This also affects your PR.

2023-04-25 13:00 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2=f"{DB_APPLICATION_NAME}:database"
True, reverted.

2023-04-27 08:36 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/src/charm.py
> +                "host": relation_data["endpoints"].split(":")[0],
Thanks, good catch, I also updated my PR

2023-04-27 09:56 UTC, ghislainbourgeois requested changes

2023-04-27 09:56 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2=f"{DB_APPLICATION_NAME}:database"
This endpoint should not be changed in this PR

2023-04-27 09:56 UTC, ghislainbourgeois commented on orc8r-bootstrapper-operator/tests/unit/test_charm.py
>      @patch("charm.ConnectionString")
I would probably remove all the patches for `ConnectionString`, it is not really required and will hide potential problems down the line.

2023-04-27 10:08 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2=f"{DB_APPLICATION_NAME}:database"
My bad, fixed.

2023-04-27 10:09 UTC, sanchezfdezjavier commented on orc8r-bootstrapper-operator/tests/unit/test_charm.py
>      @patch("charm.ConnectionString")
I agree. Done.

2023-04-27 10:21 UTC, ghislainbourgeois approved these changes

2023-04-28 06:24 UTC, ghislainbourgeois approved these changes

2023-04-28 06:42 UTC, Gmerold approved these changes

2023-04-28 07:26 UTC, saltiyazan approved these changes

2023-05-01 14:09 UTC, merged