Uses new data platform lib in orc8r-certifier
canonical/charmed-magma-orchestrator pull request #254
Opened 2023-04-24 08:48 UTC by sanchezfdezjavier

# Description

Uses new data platform lib in orc8r-certifier.

⚠️ Right now the new data platform lib does not support handling relation broken events.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-04-24 08:52 UTC, Gmerold commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:postgresql_client"
Relation name didn't change, so there's no need to update this.

2023-04-24 08:58 UTC, ghislainbourgeois requested changes

2023-04-24 08:58 UTC, ghislainbourgeois commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:postgresql_client"
The relation endpoint on `postgresql-k8s` side needs to change however. But not to `postgresql_client`, which is the interface, but to `database`: https://github.com/canonical/postgresql-k8s-operator/blob/b01f121625808ee57eff84cf274896ce8ed4f5cf/metadata.yaml#L32

We will need to update all the PRs to also update the bundle thinking about it.

2023-04-24 09:04 UTC, Gmerold commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:postgresql_client"
Yes, for some reason I thought it applies to the certifier side. Stupid... :)

2023-04-24 09:05 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:postgresql_client"
First, you're right. Second, this file is not meant to be changed in this PR, this is `nms-magmalte`. Reverted.

2023-04-24 09:08 UTC, Gmerold commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:postgresql_client"
As mentioned by @ghislainbourgeois, we need to update the bundle as well.

2023-04-24 09:36 UTC, Gmerold approved these changes

2023-04-24 09:39 UTC, sanchezfdezjavier commented on nms-magmalte-operator/tests/integration/test_integration.py
> +            relation1=CERTIFIER_APPLICATION_NAME, relation2="postgresql-k8s:postgresql_client"
Done.

2023-04-24 09:54 UTC, ghislainbourgeois requested changes

2023-04-24 09:54 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +        # )
Can't we just hand the relation broken ourselves?

2023-04-24 09:54 UTC, ghislainbourgeois commented on orc8r-certifier-operator/src/charm.py
> +            self._on_database_relation_joined,  # TODO: This should be a different event?
I am not sure what the `TODO` is meant to say here, are you talking about the method that we call to respond to the event? In this case, I think it should be renamed right away.

2023-04-24 09:54 UTC, ghislainbourgeois commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    )
The PR linked here is closed. I think we should handle `relation-broken` directly here.

2023-04-24 13:29 UTC, gruyaume commented on orc8r-certifier-operator/metadata.yaml
> +  database:
We didn't need to change "our" side of the interface

2023-04-25 14:14 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/metadata.yaml
> +  database:
I've changed it for the sake of consistency, it's pretty confusing looking at the [postgres-k8s requires](https://github.com/canonical/postgresql-k8s-operator/blob/b01f121625808ee57eff84cf274896ce8ed4f5cf/metadata.yaml#L32) and seeing we match the name for de deprecated relation but the interface for the new one. Let me know if that makes sense.

2023-04-26 15:36 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/src/charm.py
> +        # )
Done.

2023-04-26 15:36 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/src/charm.py
> +            self._on_database_relation_joined,  # TODO: This should be a different event?
Fixed.

2023-04-26 15:36 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/tests/unit/test_charm.py
> +    )
Fixed.

2023-04-27 11:10 UTC, gruyaume commented on orc8r-certifier-operator/metadata.yaml
> +  database:
Humm in this case you may want to align with @ghislainbourgeois , [this PR](https://github.com/canonical/charmed-magma-orchestrator/pull/251) for nms-magmalte uses `db` as the relation name.

2023-04-27 11:32 UTC, sanchezfdezjavier commented on orc8r-certifier-operator/metadata.yaml
> +  database:
We've already did, we agreed to set them all to `database`, this way we follow the new naming.

2023-04-27 14:09 UTC, gruyaume approved these changes

2023-04-27 14:11 UTC, ghislainbourgeois approved these changes

2023-04-28 06:26 UTC, ghislainbourgeois approved these changes

2023-04-28 06:45 UTC, Gmerold approved these changes
Good job and also good luck with the conflicts with [this guy here](https://github.com/canonical/charmed-magma-orchestrator/pull/253) ;)

2023-04-28 07:24 UTC, saltiyazan approved these changes

2023-05-02 09:15 UTC, merged