Updates updates charms using `orc8r_base_db`
canonical/charmed-magma-orchestrator pull request #256
Opened 2023-04-24 17:56 UTC by sanchezfdezjavier

# Description

Uses `orc8r_base_db` changes from this [PR](https://github.com/canonical/magma-orc8r-libs/pull/11) for all the charms using the library.  We also make the corresponding changes in the bundle.

- orc8r-accessd
- orc8r-configurator
- orc8r-ctraced
- orc8r-device
- orc8r-directoryd
- orc8r-lte
- orc8r-policydb
- orc8r-smsd
- orc8r-state
- orc8r-subscriberdb
- orc8r-subscriberdb-cache
- orc8r-tenants

⚠️ Don't merge before the referenced PR is merged and the new lib is fetched.

## Checklist

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have added tests that validate the behaviour of the software.
- [ ] I validated that new and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have bumped the version of any required library.

2023-04-24 17:57 UTC, sanchezfdezjavier commented
Thanks for reviewing this huge PR, if done separately would take ages!

2023-04-24 18:40 UTC, ghislainbourgeois requested changes

2023-04-24 18:40 UTC, ghislainbourgeois commented on orc8r-bundle/bundle.yaml.j2
> +- - orc8r-accessd:database
Our side of all the relations should stay `db`, as that is how the library finds the relation.

2023-04-25 09:31 UTC, sanchezfdezjavier commented on orc8r-bundle/bundle.yaml.j2
> +- - orc8r-accessd:database
Fixed.

2023-04-27 14:14 UTC, gruyaume commented on orc8r-accessd-operator/metadata.yaml
>    db:
Aren't we now using `database` as the relation name?

2023-04-27 16:08 UTC, sanchezfdezjavier commented on orc8r-accessd-operator/metadata.yaml
>    db:
Yes, I was reverting the change. Now it's good.

2023-04-28 06:35 UTC, ghislainbourgeois approved these changes
LGTM, but don't forget to change the relation names in the integration tests as you merge other PRs. (certifier and bootstrapper specifically)

2023-04-28 06:52 UTC, Gmerold approved these changes

2023-04-28 08:29 UTC, saltiyazan approved these changes

2023-04-28 08:54 UTC, gruyaume approved these changes
Approved (assuming CI passes)

2023-04-28 13:56 UTC, sanchezfdezjavier commented
> Approved (assuming CI passes)

Currently, we're blocked by this [postgres bug](https://warthogs.atlassian.net/browse/DPE-1470). itests fail when we remove postgres and redeploy it, it gets stuck in `awaiting cluster start`. I've talked to Marcelo, he's struggling to reproduce the issue, the only fix found was to patch the k8s endpoints, which I think is outside the scope of these PRs.

We've discussed in the daily setting the affected tests to `xfail` until the issue is fixed. Besides, `main-branch` tests are passing because we're not testing this behavior, just itests for individual charms are failing.

Let me know if that works and I push the corresponding changes.

2023-04-28 14:12 UTC, ghislainbourgeois commented
> > Approved (assuming CI passes)
> 
> Currently, we're blocked by this [postgres bug](https://warthogs.atlassian.net/browse/DPE-1470). itests fail when we remove postgres and redeploy it, it gets stuck in `awaiting cluster start`. I've talked to Marcelo, he's struggling to reproduce the issue, the only fix found was to patch the k8s endpoints, which I think is outside the scope of these PRs.
> 
> We've discussed in the daily setting the affected tests to `xfail` until the issue is fixed. Besides, `main-branch` tests are passing because we're not testing this behavior, just itests for individual charms are failing.
> 
> Let me know if that works and I push the corresponding changes.

I agree with setting the tests to `xfail`. On my side, I was able to reproduce the issue by doing `juju remove-application postgresql-k8s --force --no-wait`. I am not sure those particular steps are supposed to be working however, as they probably don't let the charm run its cleanup.

2023-05-04 13:49 UTC, merged