Test: adding unit tests to magmalte-operator to cover action events
canonical/charmed-magma-orchestrator pull request #32
Opened 2022-05-11 06:30 UTC by saltiyazan

nms-magmalte-operator has two actions that are not covered with unit tests, new test cases are added to cover them.

2022-05-11 15:00 UTC, sanchezfdezjavier commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_create_nms_admin_user_action(
I suggest following the naming convention for the test methods `test_given_x_when_y_then_z`

2022-05-13 11:08 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_create_nms_admin_user_action(
I changed the names to follow this convention :)

2022-05-16 17:40 UTC, gruyaume commented
The description should cover what has been added. You can remove the "nms-magmalte-operator has two actions that are not covered with unit tests" and reformulate to something like "Adds unit tests to validate nms-magmalte charm behaviour on juju actions"

2022-05-16 17:51 UTC, gruyaume requested changes

2022-05-16 17:51 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_callback_is_invoked_create_nms_admin_user_is_called(
when "callback is involved"?

2022-05-16 17:51 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        mock_exec.return_value = MockExec()
`mock_exec` is not even called as far as I can see, mocking its return value doesn't do anything

2022-05-16 17:51 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        _create_nms_admin_user.assert_called_once()
We don't want to validate that a private method is invoked, we want to validate the beaviour. Here the behaviour is that we exec a command in the container. This is important because if we change the internal implementation of `create_nms_admin_user_action`, this test would fail we we keep it as it is right now.

2022-05-16 17:51 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        _create_nms_admin_user.return_value = Exception()
Same comment as above, we don't want `_create_nms_admin_user` to raise the error, we would want `process.wait_output` to raise the error.

2022-05-23 10:29 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_callback_is_invoked_create_nms_admin_user_is_called(
It is correct that the name was confusing. The issue has been addressed in the latest commit.

2022-05-23 10:30 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        mock_exec.return_value = MockExec()
The issue has been addressed in the latest commit, removing this mock from all the test cases where it isn't used.

2022-05-23 10:33 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        _create_nms_admin_user.assert_called_once()
Issue has been addressed in the latest commit to validate that the _exec_ was called on the container.

2022-05-30 14:39 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    @patch("charm.MagmaNmsMagmalteCharm._get_db_connection_string", new_callable=PropertyMock)
Is this mock used at all?

2022-05-30 14:39 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_create_nms_admin_user_is_called_command_executed_on_container(
the `given` is not really correct. I'd probably use something like `given_username_email_and_password are provided_when_create_nms_admin_user_juju_action_then_pebble_command_is_executed`

2022-05-30 14:39 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_create_nms_admin_user_is_called_command_executed_on_container(
And following this, the create_nms_admin_user_action should include username, password and we should probably validate the content of the exec command.

2022-05-30 14:39 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    @patch("charm.MagmaNmsMagmalteCharm._get_admin_username")
We probably don't want to patch those private methods but simply the _stored content. This way if we change the internal implementation of the class and don't use the private methods `get_amdin_username` anymore, unit tests won't fail.

2022-05-30 14:53 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        mock_exec.return_value = MockExec(raise_exec_error=True)
You can use `side_effect` instead of return_value. You won't have to mock the whole Exec:
`mock_exec.side_effect = ExecError(["drop"], 1, "exec", "mock")`

2022-05-31 08:12 UTC, Gmerold commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    @patch("charm.MagmaNmsMagmalteCharm._relations_ready", new_callable=PropertyMock)
You don't really have to mock this property.
Since `setUp` starts an empty harness, no existing relations is implied.

2022-05-31 18:46 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    @patch("charm.MagmaNmsMagmalteCharm._relations_ready", new_callable=PropertyMock)
addressed in the latest commit, thanks

2022-05-31 18:46 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        mock_exec.return_value = MockExec(raise_exec_error=True)
addressed in the latest commit, thanks

2022-06-03 14:27 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_user_creation_fails_then_action_raises_an_error(
Specify which juju action

2022-06-14 15:58 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    @patch("charm.MagmaNmsMagmalteCharm._get_admin_username")
I agree that mocking the private functions like `_get_admin_username` isn't a good way to write this test. But the `_on_get_admin_credentials` that is being tested, will either:

1. return the credentials of the admin user in the master organisation as it looks for the credentials that are saved in the StoredState, and the credentials are saved in the StoredState only when the admin user in master is created when `on_magma_nms_magmalte_pebble_ready` runs.

2. generate a password for the admin@<domain name> and return those.

In this case if we mock the content of `_stored,` wouldn't this unit test fail in the future if we change the implementation not to use `_stored` to save credentials? just like if we don't use `get_admin_username` anymore? at the end of the day `get_admin_username` only returns the content of `_stored.`

2022-06-15 12:01 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_user_creation_fails_then_action_raises_an_error(
addressed in the latest commit.

2022-06-15 12:02 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_create_nms_admin_user_is_called_command_executed_on_container(
Name has been changed and the parameters are validated in the latest commit. thanks

2022-06-20 13:26 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        if hasattr(self, "raise_exec_error") and self.raise_exec_error:
If I'm not mistaken, the hasattr will always be true here since we have an if/else statement in the emit that sets it either way.

2022-06-20 13:26 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    CREATE_USER_ACTION_EVENT_PARAMS = {
Does this variable need to be global? It's only used at 1 place.

2022-06-20 13:26 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_relation_is_not_realized_then_get_admin_credentials_fails(
What does "Realized" mean. Relation can be "created", "joined" or even "ready" in our code but "realized" I don't know.

2022-06-20 13:35 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_relation_is_not_realized_then_get_admin_credentials_fails(
I think I used "realised" to have a more general term, as the `_relations_ready` in the charm code waits for relations to be "created", "established" or "ready" and it will return false if any of those is false. But I guess I can use the term "ready" just like the function does in its name.

2022-06-20 13:38 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    def test_given_juju_action_when_relation_is_not_realized_then_get_admin_credentials_fails(
Yeah I'd use ready for consistency

2022-06-28 14:44 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        if hasattr(self, "raise_exec_error") and self.raise_exec_error:
Correct, I addressed it in the latest commit.

2022-06-28 14:45 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +    CREATE_USER_ACTION_EVENT_PARAMS = {
Addressed in the latest commit :)

2022-07-04 12:04 UTC, gruyaume approved these changes

2022-07-05 08:58 UTC, merged