Implements TLS certificates relation
canonical/charmed-magma-orchestrator pull request #66
Opened 2022-07-08 21:20 UTC by gruyaume

Implements TLS certificates relation

2022-07-13 13:51 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        """Initializes all event that need to be observed."""
```suggestion
        """Initializes all events that need to be observed."""
```

2022-07-14 20:34 UTC, ghislainbourgeois reviewed
First pass review, I still need to play with this, it seems the tls-operator was not published properly yet to charmhub, so this does not deploy yet.

2022-07-14 20:34 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-nginx-proxy-operator/src/charm.py
> +                return False
This can be shortened to:
```suggestion
            return bool(relation)
```

2022-07-14 20:34 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-nginx-proxy-operator/src/charm.py
> +            event.defer()
I keep seeing this construct and I think it is from the doc and the example charms, but I think reversing the first condition might help legibility:
```suggestion
        if not self._container.can_connect():
            self.unit.status = WaitingStatus("Waiting for container to be ready")
            event.defer()
            return
            
        plan = self._container.get_plan()
        if plan.services != self._pebble_layer.services:
            self.unit.status = MaintenanceStatus(
                f"Configuring pebble layer for {self._service_name}"
            )
            self._container.add_layer(self._container_name, self._pebble_layer, combine=True)
            self._container.restart(self._service_name)
            logger.info(f"Restarted container {self._service_name}")
            self.unit.status = ActiveStatus()
```

What do you think?

2022-07-14 20:34 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/README.md
> +- **cert-certifier**: TODO
Can you fix those TODOs please?

2022-07-15 12:05 UTC, saltiyazan commented on orchestrator-bundle/bundle-local-federated.yaml
> +  - orc8r-certifier
Isn't an interface name needed? why not?

2022-07-15 12:07 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/README.md
> -This [Juju](https://juju.is/) Charm deploys
This seems as useful info, and directs the reader to the documentation of magmalte, why are we removing it?

2022-07-15 13:03 UTC, gruyaume commented on orchestrator-bundle/bundle-local-federated.yaml
> +  - orc8r-certifier
Only when it is ambiguous but in this case it isn't, certifier provides only 1 interface that magmalte can consume

2022-07-15 13:05 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/README.md
> -This [Juju](https://juju.is/) Charm deploys
I don't mind keeping it

2022-07-15 13:07 UTC, gruyaume commented on orchestrator-bundle/nms-nginx-proxy-operator/src/charm.py
> +            event.defer()
Yeah I agree

2022-07-15 13:11 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/README.md
> -This [Juju](https://juju.is/) Charm deploys
Sorry, looks like my comment marked a different part of the text somehow. 
yes I meant the part that comes after, about NMS, I will repost it :)

2022-07-15 13:12 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/README.md
> -built using express framework. It contains set of application and router level middlewares. It uses
reposting the previous comment here
"This seems as useful info, and directs the reader to the documentation of magmalte, why are we removing it?"

2022-07-15 13:37 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/README.md
> +- **cert-certifier**: TODO
Fixed

2022-07-15 13:37 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/README.md
> -built using express framework. It contains set of application and router level middlewares. It uses
Fixed

2022-07-15 13:38 UTC, gruyaume commented
> First pass review, I still need to play with this, it seems the tls-operator was not published properly yet to charmhub, so this does not deploy yet.

tls-certificates-operator is now published (ref: https://charmhub.io/tls-certificates-operator)

2022-07-18 10:54 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        self.admin_operator = CertAdminOperatorRequires(self, "cert-admin-operator")
it might be a good idea to create a variable to store the relation name string :)

2022-07-18 12:18 UTC, saltiyazan commented on orchestrator-bundle/orc8r-nginx-operator/src/charm.py
> +                            nodePort=31200,
Are we sure about this port?
Deployment is breaking with the following error for nginx
`lightkube.core.exceptions.ApiError: Service "orc8r-clientcert-nginx" is invalid: spec.ports[0].nodePort: Invalid value: 31200: provided port is already allocated`
which is true since we use the same port for the "orc8r-bootstrap-nginx"

2022-07-18 19:24 UTC, saltiyazan commented on orchestrator-bundle/orc8r-nginx-operator/src/charm.py
> +                            nodePort=31200,
I suggest
```suggestion
                            name="health",
                             port=80,
                             targetPort=80,
                             nodePort=31641,
                         ),
                         ServicePort(
                             name="clientcert-legacy",
                             port=443,
                             targetPort=8443,
                             nodePort=31082,
                         ),
                         ServicePort(
                             name="clientcert",
                             port=8443,
                             targetPort=8443,
                             nodePort=31811,
                         ),
```

2022-07-18 19:34 UTC, gruyaume commented on orchestrator-bundle/orc8r-nginx-operator/src/charm.py
> +                            nodePort=31200,
Yeah I removed all the nodeports, those aren't needed

2022-07-18 19:35 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        self.admin_operator = CertAdminOperatorRequires(self, "cert-admin-operator")
Agreed, fixed

2022-07-18 23:21 UTC, ghislainbourgeois requested changes

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-magmalte-operator/README.md
> +deploys which is a microservice built using express framework. It contains set of application and
I do not understand this sentence, can you rework it?

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +            )
```suggestion
            ).close()
```

This would ensure that we close the connection to the DB properly.

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-magmalte-operator/tests/integration/test_integration.py
> +    def _find_charm(charm_dir: str, charm_file_name: str) -> Union[str, None]:
```suggestion
    def _find_charm(charm_dir: str, charm_file_name: str) -> Optional[str]:
```

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-nginx-proxy-operator/tests/integration/test_integration.py
> +    def _find_charm(charm_dir: str, charm_file_name: str) -> Union[str, None]:
```suggestion
    def _find_charm(charm_dir: str, charm_file_name: str) -> Optional[str]:
```

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-bootstrapper-operator/tests/integration/test_integration.py
> +    def _find_charm(charm_dir: str, charm_file_name: str) -> Union[str, None]:
```suggestion
    def _find_charm(charm_dir: str, charm_file_name: str) -> Optional[str]:
```

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            )
```suggestion
            ).close()
```

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-nginx-operator/src/charm.py
> +                logger.info(f"Restarted srvice {self._service_name}")
```suggestion
                logger.info(f"Restarted service {self._service_name}")
```

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-nginx-operator/tests/integration/test_integration.py
> +    def _find_charm(charm_dir: str, charm_file_name: str) -> Union[str, None]:
```suggestion
    def _find_charm(charm_dir: str, charm_file_name: str) -> Optional[str]:
```

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-orchestrator-operator/src/charm.py
> +        if re.match("^[a-zA-Z0-9._-]+:[0-9]+$", elasticsearch_url):
This will match invalid hostnames and ports, I do not think it is critical to change right now, but this could be improved by splitting the string and using a library to validate: https://validators.readthedocs.io

2022-07-18 23:21 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-orchestrator-operator/tests/integration/test_integration.py
> +    def _find_charm(charm_dir: str, charm_file_name: str) -> Union[str, None]:
```suggestion
    def _find_charm(charm_dir: str, charm_file_name: str) -> Optional[str]:
```

2022-07-19 12:51 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/README.md
> +deploys which is a microservice built using express framework. It contains set of application and
There was a word missing (Magmalte), I added it. For the rest it's copy/paste from the magma official doc.

2022-07-19 12:53 UTC, gruyaume commented
> ```yaml
> applications:
>   orc8r-certifier:
>     options:
>       domain: <your domain name>
>   orc8r-nginx:
>     options:
>       domain: <your domain name>
>   tls-certificates-operator:
>     options:
>       generate-self-signed-certificates: true
> ```
> 
> Why did you remove this part? isn't it the correct overlay for self assigned certificates?

While it can be used and will be used for testing purposes, the goal of the how-to guide is not to present all the potential deployment options.

2022-07-19 12:56 UTC, gruyaume commented on orchestrator-bundle/orc8r-orchestrator-operator/src/charm.py
> +        if re.match("^[a-zA-Z0-9._-]+:[0-9]+$", elasticsearch_url):
Yeah while I agree, the scope of this PR is already huge. Here I didn't add this block, just placed it up top with all the other python properties.

2022-07-19 12:57 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-orchestrator-operator/src/charm.py
> +        if re.match("^[a-zA-Z0-9._-]+:[0-9]+$", elasticsearch_url):
I am good with keeping it that way for now, thanks!

2022-07-19 13:05 UTC, ghislainbourgeois approved these changes

2022-07-20 13:50 UTC, saltiyazan approved these changes

2022-07-20 17:58 UTC, merged