Adds additional FeG charms
canonical/charmed-magma-orchestrator pull request #69
Opened 2022-07-20 13:53 UTC by sanchezfdezjavier

Adds additional FeG charms
- New charms: `feg-aaa-server`, `feg-control-proxy`, `feg-csfb`, `feg-eap-aka`, `feg-magmad`, `feg-s6a-proxy`, `feg-swx-proxy`, `feg-td-agent-bit`
- Adds unit and integration tests for each charm.
- Adds workflows for each charm (upload workflows missing).
- Adds (local) bundle integration tests.

Current FeG deployment status:
- `feg-aaa-server`             status: 🟢 active 
- `feg-control-proxy`          status: 🟢 active
- `feg-csfb`                   status: 🟢 active 
- `feg-eap-aka`                status: 🟢 active 
- `feg-eap-sim`                status: 🟢 active 
- `feg-eventd`                 status: 🟢 active 
- `feg-health`                 status: 🟢 active 
- `feg-hello`                  status: 🟢 active 
- `feg-magmad`                 status: 🟢 active 
- `feg-radiusd`                status: 🟢 active 
- `feg-redis`                  status: 🟢 active
- `feg-s6a-proxy`              status: 🟢 active 
- `feg-s8-proxy`               status: 🟢 active 
- `feg-session-proxy`          status: 🟢 active 
- `feg-swx-proxy`              status: 🟢 active 
- `feg-td-agent-bit`           status: 🟢 active

2022-07-20 14:28 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/actions.yaml
> +get-pfx-package-password:
This change shouldn't be in this PR

2022-07-20 14:28 UTC, gruyaume commented on .github/workflows/feg.radiusd.yml
> +name: feg-radiusd
Some workflows are missing (ex. s8-proxy and more)

2022-07-20 14:28 UTC, gruyaume commented on federation-gateway-bundle/deploy.sh
> +juju deploy ./bundle-local.yaml --trust
We should also have a feg bundle directory

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eap-aka-operator/src/charm.py
> +            event.defer()
I think reversing the condition and using it as a guard clause is a bit clearer and also reduces the indentation levels. What do you think?
```suggestion
        if not self.container.can_connect():
            self.unit.status = WaitingStatus("Waiting for container to be ready...")
            event.defer()
            
        self.unit.status = MaintenanceStatus("Configuring pod")
        pebble_layer = self._pebble_layer
        plan = self.container.get_plan()
        if plan.services != pebble_layer.services:
            self.container.add_layer(self.container_name, pebble_layer, combine=True)
            self.container.replan()
            logger.info(f"Restarted container {self.service_name}")
            self.unit.status = ActiveStatus()
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eap-aka-operator/tox.ini
> +commands =
This will fix the static analysis:
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eap-sim-operator/src/charm.py
> +        if self.container.can_connect():
I would also reverse the condition here.

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eap-sim-operator/tox.ini
> +commands =
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-health-operator/src/charm.py
> +        if self.container.can_connect():
I would also reverse the condition here.

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-health-operator/tox.ini
> +commands =
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-hello-operator/src/charm.py
> +        if self.container.can_connect():
I would also reverse the condition here.

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-hello-operator/tox.ini
> +commands =
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-radiusd-operator/src/charm.py
> +        if self.container.can_connect():
I would also reverse the condition here.

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-radiusd-operator/tox.ini
> +commands =
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-radiusd-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
This version is not in the repos anymore, it will be more resilient to remove the version.
```suggestion
    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-s8-proxy-operator/src/charm.py
> +        if self.container.can_connect():
I would also reverse the condition here.

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-s8-proxy-operator/tox.ini
> +commands =
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-s8-proxy-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
```suggestion
    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-session-proxy-operator/src/charm.py
> +        if self.container.can_connect():
I would also reverse the condition here.

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-session-proxy-operator/tox.ini
> +commands =
```suggestion
    types-toml
setenv =
    PYTHONPATH = ""
commands =
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-session-proxy-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
This version does not exist in the repos anymore. It is better to remove the version.
```suggestion
    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eap-sim-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
This version does not exist in the repos anymore. It is better to remove the version.
```suggestion
    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-health-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
This version does not exist in the repos anymore. It is better to remove the version.
```suggestion
    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv
```

2022-07-20 18:28 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-hello-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
This version does not exist in the repos anymore. It is better to remove the version.
```suggestion
    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv
```

2022-07-20 18:55 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/src/charm.py
> +            event.defer()
I totally agree, much clearer and readable

2022-07-20 18:56 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-radiusd-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Agreed, I'm removing it from all of the charms

2022-07-20 19:01 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/actions.yaml
> +get-pfx-package-password:
Agreed, fixed. I don't know how that ended up there.

2022-07-20 19:02 UTC, sanchezfdezjavier commented on .github/workflows/feg.radiusd.yml
> +name: feg-radiusd
Added the missing workflows. However, the upload workflows are not there yet, as I didn't publish the charms yet.

2022-07-20 19:02 UTC, sanchezfdezjavier commented on federation-gateway-bundle/deploy.sh
> +juju deploy ./bundle-local.yaml --trust
Added

2022-07-20 19:03 UTC, sanchezfdezjavier commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-20 19:03 UTC, sanchezfdezjavier commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-20 19:03 UTC, sanchezfdezjavier commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-20 19:03 UTC, sanchezfdezjavier commented on .github/workflows/feg.health.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-20 19:03 UTC, sanchezfdezjavier commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-20 19:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-session-proxy-operator/tox.ini
> +commands =
Done

2022-07-20 19:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-session-proxy-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Done

2022-07-20 19:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-sim-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Done

2022-07-20 19:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-health-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Done

2022-07-20 19:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-hello-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Done

2022-07-20 19:08 UTC, sanchezfdezjavier commented
@ghislainbourgeois @gruyaume Should I create these early WIP draft PRs? I feel that I kinda waste your time reviewing stuff that I had as a _TODO_. However, you still catch errors that I'd make anyway, so Idk if it's worth it or not. What do you think?

2022-07-20 19:22 UTC, ghislainbourgeois commented
> @ghislainbourgeois @gruyaume Should I create these early WIP draft PRs? I feel that I kinda waste your time reviewing stuff that I had as a _TODO_. However, you still catch errors that I'd make anyway, so Idk if it's worth it or not. What do you think guys?

I have no problem reviewing draft PRs, especially if this can help you. I think that for bigger PR, it can even be beneficial and save time in the long run because we can discuss the design earlier.

2022-07-21 09:00 UTC, sanchezfdezjavier commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:00 UTC, sanchezfdezjavier commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:00 UTC, sanchezfdezjavier commented on .github/workflows/feg.hello.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:01 UTC, sanchezfdezjavier commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:01 UTC, sanchezfdezjavier commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:01 UTC, sanchezfdezjavier commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:01 UTC, sanchezfdezjavier commented on .github/workflows/feg.radiusd.yml
> +    runs-on: ubuntu-latest
Fixed

2022-07-21 09:01 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/src/charm.py
> +            event.defer()
Done

2022-07-21 09:02 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-hello-operator/src/charm.py
> +        if self.container.can_connect():
Done

2022-07-21 09:02 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-radiusd-operator/src/charm.py
> +        if self.container.can_connect():
Done

2022-07-21 09:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-radiusd-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Removed

2022-07-21 09:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-s8-proxy-operator/src/charm.py
> +        if self.container.can_connect():
Done

2022-07-21 09:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-s8-proxy-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Removed

2022-07-21 09:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-session-proxy-operator/src/charm.py
> +        if self.container.can_connect():
Done

2022-07-21 09:03 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-session-proxy-operator/tox.ini
> +    sudo apt-get --no-install-recommends -y -oDpkg::Use-Pty=0 --allow-downgrades install python3.8-venv=3.8.10-0ubuntu1~20.04.4
Removed

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/tox.ini
> +commands =
Fixed

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-sim-operator/src/charm.py
> +        if self.container.can_connect():
Done

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-sim-operator/tox.ini
> +commands =
Fixed

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-health-operator/src/charm.py
> +        if self.container.can_connect():
Done

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-health-operator/tox.ini
> +commands =
Fixed

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-hello-operator/tox.ini
> +commands =
Fixed

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-radiusd-operator/tox.ini
> +commands =
Fixed

2022-07-21 09:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-s8-proxy-operator/tox.ini
> +commands =
Fixed

2022-07-21 14:14 UTC, gruyaume commented
> @ghislainbourgeois @gruyaume Should I create these early WIP draft PRs? I feel that I kinda waste your time reviewing stuff that I had as a _TODO_. However, you still catch errors that I'd make anyway, so Idk if it's worth it or not. What do you think guys?

I mean it's up to you. If you don't want eyes to look at it I'd suggest not creating a draft PR. If you aren't sure about your solution and want people to start looking then it's a good idea.

2022-07-21 15:22 UTC, sanchezfdezjavier commented
> > @ghislainbourgeois @gruyaume Should I create these early WIP draft PRs? I feel that I kinda waste your time reviewing stuff that I had as a _TODO_. However, you still catch errors that I'd make anyway, so Idk if it's worth it or not. What do you think guys?
> 
> I mean it's up to you. If you don't want eyes to look at it I'd suggest not creating a draft PR. If you aren't sure about your solution and want people to start looking then it's a good idea.

Understood. Thanks.

2022-08-01 14:31 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +            self.container.add_layer(self.container_name, pebble_layer, combine=True)
MaintenanceStatus should probably be here before the `add_layer`

2022-08-01 14:31 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +        self.container_name = self.service_name = self.meta.name
We probably don't need to set those variables and simply refer to self.meta.name in the places where we used those variables.

2022-08-01 14:31 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/metadata.yaml
> +  Federation Gateway td-agent-bit service.
For each of the services we added we should have a better idea of what they do and provide better descriptions for them

2022-08-01 14:31 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +            self.container.add_layer(self.container_name, pebble_layer, combine=True)
Probably applicable to more than just this charm

2022-08-01 14:31 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +        self.container_name = self.service_name = self.meta.name
Probably applicable to more than just this charm

2022-08-02 08:07 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +            self.container.add_layer(self.container_name, pebble_layer, combine=True)
Agreed, done.

2022-08-02 08:07 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +        self.container_name = self.service_name = self.meta.name
Agreed, done.

2022-08-10 15:45 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/metadata.yaml
> +  Federation Gateway td-agent-bit service.
Although I managed to get some additional info, I still don't have comprehensive descriptions. However, I've created this [story](https://warthogs.atlassian.net/browse/TELCO-249) attaching the info we've got so far. This way this PR is not blocked in case I don't manage to get those if approved. Let me know if that works.

2022-08-10 15:59 UTC, gruyaume requested changes

2022-08-10 15:59 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/pyproject.toml
> +[tool.flake8]
Use the same as the other charms:

```
[tool.flake8]
max-line-length = 99
max-doc-length = 99
exclude = [".git", "__pycache__", ".tox", "build", "dist", "*.egg_info", "venv"]
select = ["E", "W", "F", "C", "N", "R", "D", "H"]
# Ignore W503, E501 because using black creates errors with this
# Ignore D107 Missing docstring in __init__
ignore = ["W503", "E501", "D107", "E203"]
# D100, D101, D102, D103: Ignore missing docstrings in tests
per-file-ignores = ["tests/*:D100,D101,D102,D103"]
docstring-convention = "google"
# Check for properly formatted copyright header in each file
copyright-check = "True"
copyright-author = "Canonical Ltd."
copyright-regexp = "Copyright\\s\\d{4}([-,]\\d{4})*\\s+%(author)s"
```

2022-08-10 15:59 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/pyproject.toml
> +[tool.flake8]
Probablt applies to all new charms here

2022-08-10 15:59 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/requirements.txt
> +lightkube
Looks like we're not using lightkube. Not sure if it's intended. It's probable that services here won't be able to communicate together if we don't specify their ports.

2022-08-10 15:59 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/LICENSE
> +
Don't add licences to new charms, we have 1 at the project level.

2022-08-10 15:59 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +                        "'/usr/local/bin/generate_fluent_bit_config.py && "
The generation of the config file should probably not be at each pebble ready event.

2022-08-10 16:11 UTC, gruyaume requested changes

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/metadata.yaml
> +# Copyright 2022 Ubuntu
Copyright should be Canonical, not Ubuntu, you can look at other projects as examples

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
We can simply use the `ops` package now.

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/charmcraft.yaml
> +parts:
No need for building git if we point to `ops` in the requirements.txt file

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +        logger.info("Pushing controller certs to container...")
It'd probably be better to use config for now instead of static files.

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/metadata.yaml
> +
We probably want persistent storage to hold the config file and certs.

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +                    "/var/opt/magma/tmp/nghttpx.conf",
Point to the variable that contains the dir (`/var/opt/magma/tmp`)

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +        """Generates nghttpx config file.
Add a comment around why we are deleting a specific line.

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +                        "command": "nghttpx --conf /var/opt/magma/tmp/nghttpx.conf "
Use the variable for `/var/opt/magma/tmp/`

2022-08-10 16:11 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +                        "/var/opt/magma/certs/controller.key "
Use the variable for `/var/opt/magma/certs`

2022-08-10 16:16 UTC, gruyaume requested changes

2022-08-10 16:16 UTC, gruyaume commented on federation-gateway-bundle/feg-bundle/README.md
> +## Usage
There is missing information in this file

2022-08-10 18:42 UTC, ghislainbourgeois requested changes

2022-08-10 18:42 UTC, ghislainbourgeois commented on federation-gateway-bundle/bundle-local.yaml
> +applications:
There is a charm in this project for `feg-redis-operator`, but it is not in the bundle. Is it normal?

2022-08-10 18:42 UTC, ghislainbourgeois commented on federation-gateway-bundle/bundle-local.yaml
> +    trust: true
Do we need trust here and for all other charms? It seems the charms do not use the Kubernetes API.

2022-08-10 18:42 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-bundle/bundle.yaml
> +    trust: true
Do we need trust here and for all other charms? It seems the charms do not use the Kubernetes API.

2022-08-10 18:42 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-bundle/bundle.yaml
> +applications:
There seems to be a lot of charms missing in this bundle file.

2022-08-10 19:00 UTC, gruyaume commented on federation-gateway-bundle/feg-td-agent-bit-operator/requirements.txt
> +lightkube
Do we know if the ports for the docker-compose deployment are specified? If not, it's possible that all services are independent but I doubt it.

2022-08-11 07:20 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/LICENSE
> +
Done.

2022-08-11 07:20 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/pyproject.toml
> +[tool.flake8]
Done.

2022-08-11 10:58 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-bundle/bundle.yaml
> +applications:
Yes, added.

2022-08-11 11:05 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-bundle/bundle.yaml
> +    trust: true
Correct, right now we're not using the k8s API, still, I think we'll need to use it (as Guillaume suggested). I still don't know how services interact with each other, and we'll not be using this file until charms are published. Should I keep it until I resolve that? What do you think?

2022-08-11 11:11 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +                    "/var/opt/magma/tmp/nghttpx.conf",
Done.

2022-08-11 11:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +        """Generates nghttpx config file.
Done. Is the description ok?

2022-08-11 11:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +                        "command": "nghttpx --conf /var/opt/magma/tmp/nghttpx.conf "
Done.

2022-08-11 11:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +                        "/var/opt/magma/certs/controller.key "
Done.

2022-08-11 11:13 UTC, sanchezfdezjavier commented on federation-gateway-bundle/bundle-local.yaml
> +    trust: true
Correct, right now we're not using the k8s API, still, I think we'll need to use it (as Guillaume suggested). I still don't know how services interact with each other, and we'll not be using this file until charms are published. Should I keep it until I resolve that? What do you think?

2022-08-11 11:20 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-aaa-server-operator/metadata.yaml
> +# Copyright 2022 Ubuntu
Done.

2022-08-11 11:21 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-aaa-server-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Done.

2022-08-11 11:21 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-aaa-server-operator/charmcraft.yaml
> +parts:
Done.

2022-08-11 11:34 UTC, sanchezfdezjavier commented on federation-gateway-bundle/bundle-local.yaml
> +applications:
No, it should be there. Added.

2022-08-11 12:33 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +        """Generates nghttpx config file.
I didn't mean to add inline comment. The comment can be part of the docstring.

2022-08-11 13:17 UTC, ghislainbourgeois commented on federation-gateway-bundle/bundle-local.yaml
> +    trust: true
I think it would be best to default to `trust: false`, and enable it only when we are sure we need, for only the charms that need it. This will improve security of the deployment, and telcos are really sensitive to security.

2022-08-11 13:45 UTC, sanchezfdezjavier commented on federation-gateway-bundle/bundle-local.yaml
> +    trust: true
Agreed, done.

2022-08-11 13:53 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-bundle/bundle.yaml
> +    trust: true
Same as above. Done.

2022-08-12 11:10 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +        """Generates nghttpx config file.
Done.

2022-08-16 11:23 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/metadata.yaml
> +
Agreed, done. I've added it for `feg-td-agent-bit` which was missing as well.

2022-08-22 09:04 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +        logger.info("Pushing controller certs to container...")
Done.

2022-08-22 09:06 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/certs-config.yaml
> +feg-control-proxy:
I don't know if you want this file to be here. I thought it'd be helpful for quicker testing. I also can leave it as a template without actual certs. Let me know what you think.

2022-08-22 12:30 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/src/charm.py
> +                        "'/usr/local/bin/generate_fluent_bit_config.py && "
Done.

2022-08-23 07:53 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-bundle/README.md
> +## Usage
I've created this [story](https://warthogs.atlassian.net/browse/TELCO-253) that includes updating this file. For the moment, I specify the bundle is not yet published and refer to the local deployment.

2022-08-23 07:53 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-bundle/README.md
> +## Usage
Let me know if that works.

2022-08-23 18:16 UTC, gruyaume requested changes

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/LICENSE
> +
No need for a license at the charm level

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/README.md
> +# feg-csfb
csfb?

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/src/charm.py
> +        )
This charm doesn't need to be exposed? If that's not the case we can drop the requirement on lightkube.

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/src/test_controller.crt
> +-----BEGIN CERTIFICATE-----
We probably don't want those files here.

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-csfb-operator/LICENSE
> +
We don't need licenses at the charm level

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-aka-operator/LICENSE
> +
We don't need licenses at the charm level

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-aka-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-aka-operator/README.md
> +juju deploy magma-feg-eap-aka  feg-eap-aka --trust
--trust is used if we make calls to k8s which we aren't doing here

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-aka-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
just use ops

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-aka-operator/requirements.txt
> +lightkube
We aren't using lightkube anywhere here.

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-sim-operator/LICENSE
> +
License is not needed at the charm level

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eap-sim-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-eventd-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-health-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-csfb-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/charmcraft.yaml
> +parts:
Please consider it as done when the changes are pushed, here we're still building `git`

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Please consider it as done when the changes are pushed, here we're still building git

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Just use ops

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-control-proxy-operator/requirements.txt
> +lightkube
We're not using lightkube anywhere

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-csfb-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Just use ops

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-csfb-operator/requirements.txt
> +lightkube
We're not using lightkube

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-radiusd-operator/LICENSE
> +
No need for license at the charm level

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-redis-operator/LICENSE
> +
Non need for a license at the charm level

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-redis-operator/README.md
> +juju deploy magma-feg-redis  feg-redis --trust
No need for trust if we're not making call to k8s.

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-redis-operator/charmcraft.yaml
> +parts:
This block is not needed

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-redis-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Just use ops

2022-08-23 18:16 UTC, gruyaume commented on federation-gateway-bundle/feg-redis-operator/src/charm.py
> +                        "command": '/bin/bash -c "/usr/local/bin/generate_service_config.py '
We probably don't want to generate the config file at each pebble ready

2022-08-23 18:18 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
It's weird, I see you changed it in your branch but here in the "files changed" I still see the old version

2022-08-23 18:18 UTC, gruyaume commented on federation-gateway-bundle/feg-aaa-server-operator/charmcraft.yaml
> +parts:
It's weird, I see you changed it in your branch but here in the "files changed" I still see the old version

2022-08-24 07:10 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Outdated

2022-08-24 07:10 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 07:13 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/LICENSE
> +
Outdated

2022-08-24 07:13 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-radiusd-operator/LICENSE
> +
Outdated

2022-08-24 07:14 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-csfb-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Outdated

2022-08-24 07:15 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Outdated

2022-08-24 13:10 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/LICENSE
> +
Outdated

2022-08-24 13:10 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/LICENSE
> +
Outdated

2022-08-24 13:11 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 13:11 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/requirements.txt
> +git+https://github.com/canonical/operator/#egg=ops
Outdated

2022-08-24 13:11 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-sim-operator/LICENSE
> +
Outdated

2022-08-24 13:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-sim-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 13:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eventd-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 13:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-health-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 13:13 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 13:13 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-csfb-operator/charmcraft.yaml
> +parts:
Outdated

2022-08-24 20:17 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/src/charm.py
> +                        "command": '/bin/bash -c "/usr/local/bin/generate_service_config.py '
Done

2022-08-24 20:18 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/README.md
> +# feg-csfb
FIxed

2022-08-24 20:40 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/requirements.txt
> +lightkube
I agree, for sure they need to be exposed. As far as I've seen there are no ports in the docker-compose file. However, there are more files in which I found some info about it, like helm charts. For instance `feg/cloud/helm/feg-orc8r/templates/feg_hello.service.yaml`, but there no more helm charts, so I still need to figure this out.

2022-08-24 20:40 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/test_controller.crt
> +-----BEGIN CERTIFICATE-----
Outdated

2022-08-24 20:41 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-csfb-operator/LICENSE
> +
Outdated

2022-08-24 23:50 UTC, ghislainbourgeois requested changes

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-control-proxy-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to use `latest` and not a specific version?

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +            return False
```suggestion
        if not key:
            return False
```

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +            return False
```suggestion
        if not certificate:
            return False
```

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eap-sim-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eventd-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to use `latest`?

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-eventd-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-health-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-hello-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-magmad-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to use `latest`?

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-magmad-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-radiusd-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-redis-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to use `latest`?

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-redis-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to use `latest`

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-redis-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-s6a-proxy-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-s8-proxy-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-session-proxy-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-swx-proxy-operator/requirements.txt
> +lightkube-models
lightkube is not used

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-td-agent-bit-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to `latest`?

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-td-agent-bit-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
Do we really want to use `latest`?

2022-08-24 23:50 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-control-proxy-operator/certs-config.yaml
> +feg-control-proxy:
I am a bit worried about leaving private keys in a repo, even if they are not used anywhere. People somewhere will use them and create big security issues. A recent example: https://programmingwithstyle.com/posts/howihackedmycar/

2022-08-25 09:04 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +            return False
Fixed

2022-08-25 09:11 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/src/charm.py
> +            return False
Fixed

2022-08-25 09:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-sim-operator/requirements.txt
> +lightkube-models
Done

2022-08-25 09:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-session-proxy-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:12 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-swx-proxy-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:25 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
No, we don't. Somehow Juju fails to push`1.6.0`, we're using `1.6.1` do you see any problem with this?

2022-08-25 09:25 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eventd-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Changed to `1.6.1`

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eventd-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-health-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-hello-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-magmad-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Changed to `1.6.1`

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-magmad-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-radiusd-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:26 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Changed to `1.6.1`

2022-08-25 09:27 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
Changed to `1.6.1`

2022-08-25 09:27 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-redis-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:27 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-s6a-proxy-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:27 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-s8-proxy-operator/requirements.txt
> +lightkube-models
Removed

2022-08-25 09:27 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/README.md
> +Default: docker.artifactory.magmacore.org/gateway_python:latest
Changed to `1.6.1`

2022-08-25 09:27 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-td-agent-bit-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
Changed to `1.6.1`

2022-08-25 09:28 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/README.md
> +juju deploy magma-feg-eap-aka  feg-eap-aka --trust
Removed

2022-08-25 09:28 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-eap-aka-operator/requirements.txt
> +lightkube
Removed

2022-08-25 09:28 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-control-proxy-operator/requirements.txt
> +lightkube
Removed

2022-08-25 09:28 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-csfb-operator/requirements.txt
> +lightkube
Removed

2022-08-25 20:40 UTC, ghislainbourgeois commented on federation-gateway-bundle/feg-control-proxy-operator/metadata.yaml
> +    upstream-source: docker.artifactory.magmacore.org/gateway_python:latest
I am good with `1.6.1`

2022-09-09 08:28 UTC, sanchezfdezjavier commented on federation-gateway-bundle/feg-aaa-server-operator/src/charm.py
> +        )
I bet It needs to be exposed. However,  I didn't figure out what to expose yet. I've dropped all the lightkube references until I figure it out.

2022-09-09 08:30 UTC, closed without merging