Telco 219 integrate orc8r with prometheus and prometheus configurer
canonical/charmed-magma-orchestrator pull request #82
Opened 2022-08-09 14:48 UTC by Gmerold

# Description

This PR implements integration of Magma Orc8r with Prometheus and Prometheus Configurer.

# Checklist:

- [X] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that validate the behaviour of the software
- [X] I validated that new and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2022-08-09 20:02 UTC, ghislainbourgeois requested changes

2022-08-09 20:02 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        return f"http://{prometheus_service_name}:9090"
Shouldn't the port be provided by the relation also?

2022-08-09 20:02 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        return f"http://{prometheus_configurer_service_name}:9100"
Shouldn't the port be provided by the relation also?

2022-08-09 20:02 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        return f"http://{alertmanager_service_name}:9093"
Shouldn't the port be provided by the relation also?

2022-08-09 20:02 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +            self.unit.status = BlockedStatus(msg)
We set `BlockedStatus` here but we never set `ActiveStatus`?

2022-08-10 18:07 UTC, gruyaume commented on orchestrator-bundle/bundle-local-federated.yaml
> +  - tls-certificates-operator
Why is this added in this PR?

2022-08-11 09:54 UTC, Gmerold commented on orchestrator-bundle/bundle-local-federated.yaml
> +  - tls-certificates-operator
I've seen `tls-certificates-operator` charm added to this bundle, but the relation was missing. Was that intentional?

2022-08-11 09:56 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        return f"http://{prometheus_service_name}:9090"
I've added TODOs to get the port number from the relation data once it's available there.

2022-08-11 09:56 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        return f"http://{alertmanager_service_name}:9093"
I've added TODOs to get the port number from the relation data once it's available there.

2022-08-11 09:56 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +        return f"http://{prometheus_configurer_service_name}:9100"
I've added TODOs to get the port number from the relation data once it's available there.

2022-08-11 09:58 UTC, Gmerold commented on orchestrator-bundle/orc8r-metricsd-operator/src/charm.py
> +            self.unit.status = BlockedStatus(msg)
New implementation doesn't use the `orc8r_base` lib anymore and `ActiveStatus` is now set by the charm after configuring pebble layer.

2022-08-11 13:25 UTC, ghislainbourgeois approved these changes

2022-08-11 14:05 UTC, gruyaume approved these changes

2022-08-12 14:22 UTC, merged