Uses the tls-certificates interface `v1`
canonical/charmed-magma-orchestrator pull request #83
Opened 2022-08-12 17:10 UTC by gruyaume

# Description

- Uses the tls-certificates interface `v1`
- Decouples private key creation from certificate creation

# Checklist:

- [ ] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [ ] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-12 21:09 UTC, ghislainbourgeois requested changes
I did a quick first pass but did not go through all the code yet.

2022-08-12 21:09 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/pyproject.toml
> +mypy_path = "$MYPY_CONFIG_FILE_DIR/src:$MYPY_CONFIG_FILE_DIR/lib/charms/magma_orc8r_certifier:$MYPY_CONFIG_FILE_DIR/tests/unit"
This change breaks mypy checking of imports.

2022-08-12 21:09 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +from charms.magma_orc8r_certifier.v0.cert_admin_operator import (  # type: ignore[import]
All the `type: ignore[import]` comments added in this PR should be removed after fixing pyproject.toml.

2022-08-15 21:26 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +from charms.magma_orc8r_certifier.v0.cert_admin_operator import (  # type: ignore[import]
Fixed

2022-08-15 21:27 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/pyproject.toml
> +mypy_path = "$MYPY_CONFIG_FILE_DIR/src:$MYPY_CONFIG_FILE_DIR/lib/charms/magma_orc8r_certifier:$MYPY_CONFIG_FILE_DIR/tests/unit"
Fixed

2022-08-17 01:24 UTC, ghislainbourgeois requested changes

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-bundle/README.md
> +> **Warning**: This configuration is unsecure because it uses self-signed certificates.
I think it would be better to provide both ways (self-signed vs passing certificates), this would let the user know the alternative. If not, the user will have to know to go look up the documentation for `tls-certificates-operator`.

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        )
This line is doubled.

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            bool: True/False
I prefer the previous line here, we already know that a `bool` is `True` or `False`.
```suggestion
            bool: Whether root certificate are pushed to workload.
```

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        return True
Is it intentional that we return `True` in this case?

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _on_config_changed(self, event: ConfigChangedEvent):  # noqa: C901
I am not a fan of ignoring `C901`, I think it usually is right. In this case, we could split this method in two:

```
    def _on_config_changed(self, event: ConfigChangedEvent):
         if self.unit.is_leader():
             self._on_leader_config_change()
         else:
             self._on_non_leader_config_change()
```

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self._request_certificate_based_on_stored_csr()
This will be called whenever the `tls-certificates` provider is scaled up, will this be a problem?

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                self._push_application_certificates()
```suggestion
            if not self._application_certificates_are_stored or not self._stored_application_certificate_matches_config:
                self._generate_application_certificates()
                self._push_application_certificates()
```

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
>          """Juju event triggered when pebble is ready.
Can you fix the docstring?

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            logger.info("Certificate's CSR doesn't match stored root CSR")
In this case should we change the status to `BlockedStatus`?

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        """Pushes application certificates to the workload container.
```suggestion
        """Pushes application private keys to the workload container.
```

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        """Pushes root certificates to workload container.
```suggestion
        """Pushes root private key to workload container.
```

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        logger.info("Stored application certificates dont match config")
```suggestion
        logger.info("Stored application certificates does not match config")
```

2022-08-17 01:24 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            return False
Is there a reason to use an assertion here instead of `if`?

2022-08-17 10:10 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self.framework.observe(self.on.config_changed, self._on_config_changed)
Is there any reason why this `observe` is here alone, instead of at the bottom with the rest of them?

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +                "ca-common-name": DOMAIN
According to the `README` above, shouldn't that be `f"rootca.{DOMAIN}"`?

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/tests/unit/certificates.py
> +    validity: int = 24 * 365,
```suggestion
    validity: int = 365 * 24,
```
I know it's a cosmetic change, but at first glance it looks like the default cert validity was 24 years ;)

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        return True
I'd say yes, but anyway, `return False` is missing from the last `if`. Isn't it?

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._domain_config:
You might wanna use `validators.domain` for stronger validation.

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _on_config_changed(self, event: ConfigChangedEvent):  # noqa: C901
+1

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not domain_name:
Is this check needed?

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._domain_config_is_valid:
Is this check needed? 
BTW, considering the current implementation of this check, it does the same as the `if not domain_name` above.

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._root_private_key:
Is this check needed?

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
>              logger.info("Cant connect to container - Won't push certificates to workload")
Don't we wanna change the status to `WaitingStatus`?

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            logger.info("Certificate's CSR doesn't match stored root CSR")
I don't think we need to. `BlockedStatus` typically indicates need for user's intervention. 
If I'm not mistaken, this check can fail only if someone changes the `domain` or deletes the `CSR` in the time between requesting and issuing the cert.
I'd increase the log level though.

2022-08-17 10:48 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _push_metricsd_config_file(self) -> None:
Shouldn't this file also contain keys for Prometheus Configurer and Alertmanager Configurer?

2022-08-17 11:08 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _on_replicas_relation_joined(self, event: RelationJoinedEvent):
Is there any reason behind not having a docstring for this method?

2022-08-17 12:00 UTC, gruyaume commented on orchestrator-bundle/orc8r-bundle/README.md
> +> **Warning**: This configuration is unsecure because it uses self-signed certificates.
We will have to think a bit more about how people will provide signed certificates of their own. There are multiple options:
1. The user provides certifier with a private key in the config and the tls-certficates-operator with both the cert and ca cert.
2. The user retrieves the CSR from certifier and then generates/provides certs that they insert into tls-cerrificates-operator

I think option 1 is the way to go but I didn't want to bundle this discussion with this already super large PR.

2022-08-17 13:16 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _on_config_changed(self, event: ConfigChangedEvent):  # noqa: C901
I agree too, but something more like 
```
    def _on_config_changed(self, event: ConfigChangedEvent):
        if not self._container.can_connect():
               self.unit.status = WaitingStatus("Waiting for container to be ready")
               event.defer()
               return
         if self.unit.is_leader():
             self._on_leader_config_change()
         else:
             self._on_non_leader_config_change()
```

2022-08-17 13:21 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                return
like above this also can be one condition, the root csr is new in both cases, isn't it? or do we need to distinguish between the two?
```suggestion
            if not self._root_csr_is_stored or not self._stored_root_csr_matches_config:
                self.unit.status = WaitingStatus("Waiting for leader to generate a new root csr")
                event.defer()
                return
```

2022-08-17 13:25 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _push_metricsd_config_file(self) -> None:
as far as I know, those are the only things it needs

2022-08-17 13:27 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        )
Fixed

2022-08-17 13:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        return True
Fixed now.

2022-08-17 13:30 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self.framework.observe(self.on.config_changed, self._on_config_changed)
Fixed

2022-08-17 13:34 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            logger.info("Certificate's CSR doesn't match stored root CSR")
But if this check fails, won't the charm be effectively blocked until a user intervenes to fix the issue?

2022-08-17 13:39 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            logger.info("Certificate's CSR doesn't match stored root CSR")
Changing the `domain` will trigger `config_changed` event, in which case the charm should recover automatically. Not sure about deleting the CSR manually, but that seems like a wild thing to do, doesn't it?

2022-08-17 13:41 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            logger.info("Certificate's CSR doesn't match stored root CSR")
Yes, good point

2022-08-17 14:56 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._domain_config:
I'm not certain we want to add this project as a dependency, but I'm happy to steal their regex

2022-08-17 15:22 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                self._push_application_certificates()
`_stored_application_certificate_matches_config` raises if there is no stored certificate, hence why I placed them on 2 separate lines

2022-08-17 15:22 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                return
`_stored_application_certificate_matches_config` raises if there is no stored certificate, hence why I placed them on 2 separate lines

2022-08-17 15:26 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not domain_name:
Yeah I think so, if in the future we call generate_root_csr without a domain name, we'd want it to error our properly.

2022-08-17 15:28 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._root_private_key:
Yes, we don't want to push an empty root private key. In the charm today this should never be triggered by nothing prevents us in the future from using this method and ending up pushing an empty private key without erroring out

2022-08-17 15:32 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                self._push_application_certificates()
In my suggested change, since the check for stored certificate is before, the second check will not be run in that case, because the first element of the `or` is `True`, so the rest does not matter.

2022-08-17 15:33 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._domain_config_is_valid:
Just used the domain_config_is_valid and removed the other.

2022-08-17 15:33 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _on_config_changed(self, event: ConfigChangedEvent):  # noqa: C901
Fixed

2022-08-17 15:34 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._domain_config:
Done

2022-08-17 15:45 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            return False
Naa, moved it to a if

2022-08-17 15:50 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _on_replicas_relation_joined(self, event: RelationJoinedEvent):
No, forgot about it but this method doesn't exist anymore

2022-08-17 15:56 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                return
Fixed

2022-08-17 15:56 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
>              logger.info("Cant connect to container - Won't push certificates to workload")
Fixed

2022-08-17 15:58 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +                "ca-common-name": DOMAIN
Sure fixed

2022-08-17 15:58 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                self._push_application_certificates()
Good point, fixed

2022-08-17 15:58 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
>          """Juju event triggered when pebble is ready.
Done

2022-08-17 15:59 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        self._request_certificate_based_on_stored_csr()
Fixed, now being called on relation created only.

2022-08-17 17:55 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-bundle/README.md
> +> **Warning**: This configuration is unsecure because it uses self-signed certificates.
As discussed in the daily, I agree that it needs to be done separately from this PR.

2022-08-18 11:59 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +                return
A little bit less nesting?
```suggestion
        elif not self._bootstrapper_private_key_is_stored:
+            self.unit.status = WaitingStatus(
+                "Waiting for leader to generate bootstrapper private key"
+            )
+            event.defer()
+            return
```

2022-08-18 12:23 UTC, gruyaume commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +                return
Done

2022-08-18 12:31 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                return
> `_stored_application_certificate_matches_config` raises if there is no stored certificate, hence why I placed them on 2 separate lines

Was this reply intended to this comment? if so I don't fully get it :D

2022-08-18 12:36 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +                return
Yeah it's fixed now anywaybut yes what I meant was that the second `if` would raise an exception if the root csr isn't stored but like Ghislain mentioned above, we will never get in that situation given the first if would catch it.

2022-08-18 12:38 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +        """Returns whether certificates are stored in relation data.
it seems to me as it checks if the `private key` is stored not `certificates`

```suggestion
        """Returns whether bootstrapper private key is stored in relation data.
```

2022-08-18 12:38 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +            bool: Whether certificates have been generated.
same as above
```suggestion
            bool: Whether private key has been stored.
```

2022-08-18 12:47 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bootstrapper-operator/metadata.yaml
> +    interface: orc8r-certifier-replica
shouldn't it be `orc8r-bootstrapper-replica` ?

2022-08-18 13:13 UTC, gruyaume commented on orchestrator-bundle/orc8r-bootstrapper-operator/metadata.yaml
> +    interface: orc8r-certifier-replica
Fixed, good catch

2022-08-18 13:32 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bootstrapper-operator/metadata.yaml
> -    interface: cert-bootstrapper
Could you please remove this relation from `bundle.yaml`, `bundle-local.yaml` and `bundle-local-federated.yaml`?

2022-08-18 13:35 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        """Returns whether the replicas  relation is created.
```suggestion
        """Returns whether the replicas relation is created.
```

2022-08-18 13:45 UTC, saltiyazan commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +                "ca-common-name": f"rootca.{DOMAIN}",
I think this should be added to all integration tests that deploy `tls-certificate-operator`

- `nms-magmalte`
- `nms-nginx-proxy`
- `orc8r-nginx`
- `orc8r-metricsd`
- `orc8r-orchestrator`

2022-08-18 13:46 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            self.unit.status = WaitingStatus("Waiting for application private key to be generated")
```suggestion
            self.unit.status = WaitingStatus("Waiting for application private keys to be generated")
```

2022-08-18 14:40 UTC, ghislainbourgeois requested changes

2022-08-18 14:40 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +    def _on_magma_orc8r_bootstrapper_pebble_ready(self, event: Union[PebbleReadyEvent]) -> None:
```suggestion
    def _on_magma_orc8r_bootstrapper_pebble_ready(self, event: PebbleReadyEvent) -> None:
```

2022-08-18 14:40 UTC, ghislainbourgeois commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +    def _configure_pebble(self, event: Union[PebbleReadyEvent]) -> None:
```suggestion
    def _configure_pebble(self, event: PebbleReadyEvent) -> None:
```

2022-08-18 15:32 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +            None
Which criteria are we following for including `Args` and `Returns` sections in docstrings? I see we are removing those from some methods.

2022-08-18 16:53 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/tests/integration/test_integration.py
> +                "ca-common-name": f"rootca.{DOMAIN}",
Fixed

2022-08-18 16:54 UTC, gruyaume commented on orchestrator-bundle/orc8r-bootstrapper-operator/src/charm.py
> +            None
I removed those that were trivial (ex. returning a bool) and kept those where there was value in explaining what the return values were.

2022-08-18 16:57 UTC, gruyaume commented on orchestrator-bundle/orc8r-bootstrapper-operator/metadata.yaml
> -    interface: cert-bootstrapper
Done

2022-08-18 18:16 UTC, ghislainbourgeois approved these changes

2022-08-19 08:00 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-bootstrapper-operator/tests/unit/test_charm.py
> +        )
An empty private key would still pass the test? I guess `load_pem_private_key` is the method from `cryptography` module you were talking about so that's also checked. Is that right?

2022-08-19 08:09 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-bootstrapper-operator/tests/unit/test_charm.py
>          )
Aren't we either asserting the wrong thing or the test name is wrong?

2022-08-19 08:12 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-bootstrapper-operator/tests/unit/test_charm.py
>          )
I'm not sure, but from the test above I guess the name should be something like `test_..._then_status_is_waiting`

2022-08-19 08:41 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        return True
How about outsourcing this logic to a separate method, I see we're repeating it several times for each certificate

2022-08-19 10:07 UTC, sanchezfdezjavier requested changes

2022-08-19 10:07 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            raise ValueError("Domain config is not valid")
Why are we rising instead of setting status as blocked? Wouldn't the charm need user intervention for setting up a new valid domain?

2022-08-19 12:21 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        return True
I'm not sure I get what would be in this method?

2022-08-19 12:24 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            raise ValueError("Domain config is not valid")
This is a helper method, we don't want it to set status. In theory, the raise will never occur because the method that actually handles the event will check if the relation exists.

2022-08-19 12:26 UTC, gruyaume commented on orchestrator-bundle/orc8r-bootstrapper-operator/tests/unit/test_charm.py
> +        )
No, `load_pem_private_key` would raise if the key is empty. Yes, the method is part of the cryptography library.

2022-08-19 12:28 UTC, gruyaume commented on orchestrator-bundle/orc8r-bootstrapper-operator/tests/unit/test_charm.py
>          )
Good catch, fixed

2022-08-19 12:59 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            raise ValueError("Domain config is not valid")
Got it, thanks

2022-08-19 14:20 UTC, sanchezfdezjavier commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        return True
Nevermind. It can't be done, my bad.

2022-08-19 14:21 UTC, sanchezfdezjavier approved these changes
LGTM

2022-08-22 10:41 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bundle/README.md
> +      ca-common-name: rootca.<your domain name>
Does this affect the 'how-to' guide on magma's official documentation?
https://docs.magmacore.org/docs/next/orc8r/deploy_using_juju

2022-08-22 10:52 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bundle/bundle.yaml
> -    trust: true
could you please remove 
```
- - orc8r-bootstrapper
  - orc8r-certifier
 ```

2022-08-22 11:58 UTC, gruyaume commented on orchestrator-bundle/orc8r-bundle/README.md
> +      ca-common-name: rootca.<your domain name>
yes

2022-08-22 11:59 UTC, gruyaume commented on orchestrator-bundle/orc8r-bundle/bundle.yaml
> -    trust: true
Done

2022-08-22 12:08 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +    def _push_metricsd_config_file(self) -> None:
OK, just asking, because in the `metricsd` charm these additional keys are needed.

2022-08-22 12:13 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not self._root_private_key:
Yes, my point was that before the changes, private key availability was already assured by the time this piece of code could be executed, so I thought this wasn't needed.
In the current implementation there's only one place when it's checked.

2022-08-22 12:17 UTC, gruyaume commented on orchestrator-bundle/orc8r-bundle/README.md
> +      ca-common-name: rootca.<your domain name>
https://github.com/magma/magma/pull/13681

2022-08-22 12:19 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not domain_name:
Yes, my point was that validity of the domain is already ensured at this point. We run `generate_root_csr` in `_on_certificate_expiring` and `_on_leader_config_changed`. Both mentioned functions validate domain config anyway.

2022-08-22 12:33 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +        if not domain_name:
I see the change is "outdated" here. You can look at the current implementation and tell me what you think. The general idea though was that this method doesn't know what was executed before. It's not great to have to do steps before calling a method if you don't want it it crash. Btw it'd still error our in this case but cleanlier and with a proper error message.

2022-08-22 12:41 UTC, Gmerold commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            raise ValueError("Domain config is not valid")
Right, that was my question exactly in another convo: why do we need this check if it will never occur?

2022-08-22 12:47 UTC, gruyaume commented on orchestrator-bundle/orc8r-certifier-operator/src/charm.py
> +            raise ValueError("Domain config is not valid")
Same answer as in the other place. This method doesn't know what was called before. Right now it'd never raise **but** if you end up using it somewhere else in a couple of weeks, how would you know that you need to do X before invoking it.

2022-08-22 14:00 UTC, saltiyazan approved these changes

2022-08-22 14:33 UTC, Gmerold approved these changes

2022-08-22 15:29 UTC, merged