nms-magmalte implements grafana-auth lib as a provider of the authentication configuration
canonical/charmed-magma-orchestrator pull request #99
Opened 2022-09-07 13:42 UTC by saltiyazan

# Description

nms-magmalte implements grafan-auth lib and provides the authentication configuration needed (auth proxy).

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-07 20:37 UTC, gruyaume requested changes

2022-09-07 20:37 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +            self.grafana_url = event.urls[0]
Setting this attribute won't persist on subsequent events. You better use peer relation data. In this case, the relation is called "replicas"

2022-09-12 13:28 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +        url = self.harness.charm._grafana_url
Don't validate that a property is set (what if we change the property name in the future). Fetch the relation data and look into it for the value.

2022-09-12 13:28 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/tests/unit/test_charm.py
> +                        "USER_GRAFANA_ADDRESS": "auth-requirer:3000",
use the variable `GRAFANA_URLS`, here we don't want `USER_GRAFANA_ADDRESS` to specifically be "auth-requirer" but the content of that variable, whatever it ends up being.

2022-09-12 13:28 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +    def _on_grafana_urls_available(self, event):
Can add typing for the event

2022-09-22 16:00 UTC, gruyaume commented on orchestrator-bundle/orc8r-bundle/bundle.yaml.j2
> +      enable_auto_assign_org: false
I thought this was supposed to be true?

2022-09-23 19:19 UTC, ghislainbourgeois requested changes

2022-09-23 19:19 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        return app_data.get("grafana_url")
```suggestion
        return app_data.get("grafana_url")
```

2022-09-23 19:19 UTC, ghislainbourgeois commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        if not self._grafana_url:
With this, it makes it impossible to change the grafana url after the fact. I don't think we expect it to really change, but I could be wrong. Do you have an opinion on this?

2022-09-23 19:59 UTC, gruyaume commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        if not self._grafana_url:
While this might "never" happen, it'd be pretty simple from our side to support a change of url, and it's a good practice for any relation data.

2022-09-26 10:40 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        return app_data.get("grafana_url")
Done

2022-09-26 10:41 UTC, saltiyazan commented on orchestrator-bundle/nms-magmalte-operator/src/charm.py
> +        if not self._grafana_url:
Correct, I was worried that this event would be emitted quire frequently even if the urls don't change. 
But I fixed it now :)

2022-09-26 10:50 UTC, saltiyazan commented on orchestrator-bundle/orc8r-bundle/bundle.yaml.j2
> +      enable_auto_assign_org: false
It is true by default.
Based on the [documentation](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#auto_assign_org) it should be set to false to create an organisation for each username, if it is true it will assign the user to the main org.
Looking at the [code](https://github.com/magma/magma/blob/35fbec2800f8b14ab2f71c3ce4406026a80f4ead/nms/server/grafana/handlers.ts#L192) of magma, I see that it expects grafana to create an org for each user, therefore it needs to be false.
Let me know if you think otherwise :)

2022-09-26 12:15 UTC, gruyaume commented on orchestrator-bundle/orc8r-bundle/bundle.yaml.j2
> +      enable_auto_assign_org: false
Let's do whatever is done in the upstream Magma, I just thought it was est to `true` up there.

2022-09-26 14:27 UTC, gruyaume approved these changes

2022-09-26 14:47 UTC, ghislainbourgeois approved these changes

2022-10-05 23:25 UTC, ghislainbourgeois approved these changes

2022-10-06 12:34 UTC, gruyaume approved these changes

2022-10-06 12:35 UTC, merged